export const SCENARIO_FAMILIES = [
  'grant_discovery',
  'foundation_discovery',
  'charity_delivery_match',
  'social_enterprise_delivery_match',
  'need_gap_search',
];

export const ARCHETYPES = [
  {
    id: 'act-indigenous-arts-qld',
    title: 'A Curious Tractor seeking Indigenous community arts funding in Queensland',
    seekerType: 'charity',
    themes: ['indigenous', 'arts', 'community'],
    states: ['QLD', 'NT'],
    beneficiaries: ['First Nations', 'Youth'],
    preferIndigenous: true,
    preferCommunityControlled: true,
    preferRegional: true,
    needFirst: false,
  },
  {
    id: 'remote-youth-justice',
    title: 'Philanthropy team looking for underserved youth justice organisations in remote Australia',
    seekerType: 'philanthropy',
    themes: ['justice', 'community', 'youth'],
    states: ['QLD', 'NT', 'WA'],
    beneficiaries: ['Youth', 'First Nations', 'Victims of Crime'],
    preferIndigenous: true,
    preferCommunityControlled: true,
    preferRegional: true,
    needFirst: true,
  },
  {
    id: 'csr-social-enterprise-employment',
    title: 'Corporate CSR lead looking for social enterprises with employment pathways',
    seekerType: 'corporate',
    themes: ['employment', 'community', 'education'],
    states: ['QLD', 'NSW', 'VIC'],
    beneficiaries: ['Youth', 'Unemployed', 'First Nations'],
    preferIndigenous: true,
    preferCommunityControlled: false,
    preferRegional: false,
    needFirst: false,
  },
  {
    id: 'foundation-before-intro-campaign',
    title: 'Charity looking for aligned foundations before an introduction campaign',
    seekerType: 'charity',
    themes: ['community', 'health', 'education'],
    states: ['QLD', 'NSW', 'VIC'],
    beneficiaries: ['Children', 'Families', 'Financially Disadvantaged'],
    preferIndigenous: false,
    preferCommunityControlled: false,
    preferRegional: false,
    needFirst: false,
  },
  {
    id: 'regional-regenerative',
    title: 'Regional regenerative and environment initiative seeking capital',
    seekerType: 'social_enterprise',
    themes: ['environment', 'regenerative', 'community'],
    states: ['QLD', 'WA', 'SA'],
    beneficiaries: ['General Community', 'Rural & Remote'],
    preferIndigenous: false,
    preferCommunityControlled: false,
    preferRegional: true,
    needFirst: true,
  },
  {
    id: 'first-nations-leadership-women',
    title: 'First Nations women and leadership initiative seeking the right funding network',
    seekerType: 'community_org',
    themes: ['indigenous', 'community', 'education'],
    states: ['QLD', 'NT', 'WA'],
    beneficiaries: ['First Nations', 'Females', 'Youth'],
    preferIndigenous: true,
    preferCommunityControlled: true,
    preferRegional: true,
    needFirst: true,
  },
  {
    id: 'housing-homelessness-remote',
    title: 'Need-first search for housing and homelessness support in remote communities',
    seekerType: 'funder',
    themes: ['community', 'housing', 'health'],
    states: ['NT', 'WA', 'SA'],
    beneficiaries: ['Homelessness Risk', 'Financially Disadvantaged', 'First Nations'],
    preferIndigenous: true,
    preferCommunityControlled: true,
    preferRegional: true,
    needFirst: true,
  },
  {
    id: 'disability-services-qld',
    title: 'Queensland disability and community inclusion search',
    seekerType: 'charity',
    themes: ['community', 'health', 'education'],
    states: ['QLD'],
    beneficiaries: ['Disability', 'Children', 'Families'],
    preferIndigenous: false,
    preferCommunityControlled: false,
    preferRegional: false,
    needFirst: false,
  },
  {
    id: 'culture-language-community',
    title: 'Community-led culture, language, and arts funding network',
    seekerType: 'community_org',
    themes: ['arts', 'community', 'indigenous'],
    states: ['QLD', 'NT', 'WA'],
    beneficiaries: ['First Nations', 'Children', 'Youth'],
    preferIndigenous: true,
    preferCommunityControlled: true,
    preferRegional: true,
    needFirst: false,
  },
  {
    id: 'education-training-regional',
    title: 'Regional education and training pathways for under-served communities',
    seekerType: 'social_enterprise',
    themes: ['education', 'employment', 'community'],
    states: ['QLD', 'WA', 'NT'],
    beneficiaries: ['Youth', 'Unemployed', 'Rural & Remote'],
    preferIndigenous: true,
    preferCommunityControlled: false,
    preferRegional: true,
    needFirst: true,
  },
];
