-- ORIC rung 3 coda: the 122 name-resolved register corps (no ABN in ORIC) — Ben's verdicts 2026-08-09.
-- NOT an ingest: all 122 already exist (AU-ORIC-<icn> scheme, 4,081 rows; some under AU-ABN with
-- ABNs ORIC doesn't record). The batch merges joined by ABN only, so these were misfiled NOROW.
-- 98 placements (both rows of dupe pairs get the same council; 29 pairs -> dedup lane) +
-- Tjirrkarli pair Laverton -> East Pilbara (Ben: follow ABS GIBSON DESERT NORTH).
-- Living Water UPC Yuendumu: inversion rule — placed Central Desert via postal, Alice street line refused.
-- Keyed on gs_id (no ABN); localities pre-resolved through the same auth table + Ben's standing calls
-- (own-name towns, alias renames, Gununa-class pinned values, hub skips stay skipped).
WITH targets(gs_id, guard, lga_name, lga_code, stamp) AS (VALUES
  ('AU-ORIC-10329','','Unincorporated NT','79399','oric_register_address+abs_asgs'), -- Anju Yinirrikun Aboriginal Corporation @ CHARLOTTE (0822)
  ('AU-ORIC-7513','','Groote Archipelago','71700','oric_register_address+abs_asgs'), -- Aruburabura Aboriginal Corporation @ ANGURUGU (0822)
  ('AU-ORIC-11813','','Litchfield','72300','oric_register_address+abs_asgs'), -- Boorooberongal Gulyangarri Aboriginal Corporation @ LLOYD CREEK (0822)
  ('AU-ORIC-7444','','Victoria Daly','74550','oric_register_address+abs_asgs'), -- Dak Milng Aboriginal Corporation @ NAUIYU (0822)
  ('AU-ABN-61377412978','','East Arnhem','71500','oric_register_address+abs_asgs'), -- Golarri Aboriginal Corporation @ GALIWINKU (0822)
  ('AU-ORIC-9849','','East Arnhem','71500','oric_register_address+abs_asgs'), -- Golarri Aboriginal Corporation @ GALIWINKU (0822)
  ('AU-ORIC-8630','','East Arnhem','71500','oric_register_address+abs_asgs'), -- Gurilka Indigenous Corporation @ GALIWINKU (0822)
  ('AU-ORIC-2498','','East Arnhem','71500','oric_register_address+abs_asgs'), -- Lanarra Homelands Aboriginal Corporation @ MILINGIMBI (0822)
  ('AU-ORIC-8393','','Roper Gulf','73600','oric_register_address+abs_asgs'), -- Magalawa Indigenous Corporation @ NUMBULWAR (0822)
  ('AU-ORIC-9858','','Tiwi Islands','74050','oric_register_address+abs_asgs'), -- Mamirnikuwi Rangers Indigenous Corporation @ PIRLANGIMPI (0822)
  ('AU-ABN-75603677183','','West Arnhem','74660','oric_register_address+abs_asgs'), -- Muburridj Aboriginal Corporation @ GUNBALANYA (0822)
  ('AU-ORIC-9641','','West Arnhem','74660','oric_register_address+abs_asgs'), -- Muburridj Aboriginal Corporation @ GUNBALANYA (0822)
  ('AU-ABN-94295724120','','West Arnhem','74660','oric_register_address+abs_asgs'), -- Namurgardabu Aboriginal Corporation @ GUNBALANYA (0822)
  ('AU-ORIC-9643','','West Arnhem','74660','oric_register_address+abs_asgs'), -- Namurgardabu Aboriginal Corporation @ GUNBALANYA (0822)
  ('AU-ABN-84802467418','','Groote Archipelago','71700','oric_register_address+abs_asgs'), -- Numayanga Aboriginal Corporation @ UMBAKUMBA (0822)
  ('AU-ORIC-2763','','Groote Archipelago','71700','oric_register_address+abs_asgs'), -- Numayanga Aboriginal Corporation @ UMBAKUMBA (0822)
  ('AU-ABN-34553639956','','Tiwi Islands','74050','oric_register_address+abs_asgs'), -- Tampu King Aboriginal Corporation @ WURRUMIYANGA (0822)
  ('AU-ORIC-9934','','Tiwi Islands','74050','oric_register_address+abs_asgs'), -- Tampu King Aboriginal Corporation @ WURRUMIYANGA (0822)
  ('AU-ORIC-11784','','Belyuen','70540','oric_register_address+abs_asgs'), -- Tjaetaba Aboriginal Corporation @ BELYUEN (0822)
  ('AU-ORIC-2668','','Victoria Daly','74550','oric_register_address+abs_asgs'), -- Camfield Mudbura Aboriginal Corporation @ VICTORIA RIVER (0852)
  ('AU-ORIC-9845','','Victoria Daly','74550','oric_register_address+abs_asgs'), -- Daguragu Community Store Aboriginal Corporation @ DAGURAGU (0852)
  ('AU-ABN-38625996362','','Victoria Daly','74550','oric_register_address+abs_asgs'), -- Djuliki Aboriginal Corporation @ TIMBER CREEK (0852)
  ('AU-ORIC-7455','','Victoria Daly','74550','oric_register_address+abs_asgs'), -- Djuliki Aboriginal Corporation @ TIMBER CREEK (0852)
  ('AU-ORIC-740','','Victoria Daly','74550','oric_register_address+abs_asgs'), -- Lingarra - Ngaringman Aboriginal Corporation @ YARRALIN (0852)
  ('AU-ABN-14781857405','','Victoria Daly','74550','oric_register_address+abs_asgs'), -- Nguwulidi Aboriginal Corporation @ TIMBER CREEK (0852)
  ('AU-ORIC-9486','','Victoria Daly','74550','oric_register_address+abs_asgs'), -- Nguwulidi Aboriginal Corporation @ TIMBER CREEK (0852)
  ('AU-ORIC-7071','','Victoria Daly','74550','oric_register_address+abs_asgs'), -- Walmoong Aboriginal Corporation @ TIMBER CREEK (0852)
  ('AU-ORIC-1556','','Central Desert','70620','oric_register_address+abs_asgs'), -- Alcoota Aboriginal Corporation @ ENGAWALA (0872)
  ('AU-ORIC-2218','','Barkly','70420','oric_register_address+abs_asgs'), -- Areyn Aboriginal Corporation @ CANTEEN CREEK (0872)
  ('AU-ORIC-9194','','Barkly','70420','oric_register_address+abs_asgs'), -- Canteen Creek Landholding Aboriginal Corporation @ CANTEEN CREEK (0872)
  ('AU-ORIC-9777','','Central Desert','70620','oric_register_address+abs_asgs'), -- Double Y Traditional Owners Association Aboriginal Corporation @ YUENDUMU (0872)
  ('AU-ABN-17317926732','','Barkly','70420','oric_register_address+abs_asgs'), -- Honeymoon Bore, akngerr-rnem akarreryel - Women?s Aboriginal Corporation @ AMPILATWATJA (0872)
  ('AU-ORIC-9159','','Barkly','70420','oric_register_address+abs_asgs'), -- Honeymoon Bore, akngerr-rnem akarreryel - Women?s Aboriginal Corporation @ AMPILATWATJA (0872)
  ('AU-ORIC-2073','','MacDonnell','72330','oric_register_address+abs_asgs'), -- Irtnwere Tyewelkere Aboriginal Corporation @ MOUNT ZEIL (0872)
  ('AU-ORIC-989','','MacDonnell','72330','oric_register_address+abs_asgs'), -- Itperlyenge Aboriginal Corporation @ HUGH (0872)
  ('AU-ORIC-988','','MacDonnell','72330','oric_register_address+abs_asgs'), -- Labrabuntja Aboriginal Corporation @ HERMANNSBURG (0872)
  ('AU-ORIC-10442','','MacDonnell','72330','oric_register_address+abs_asgs'), -- M''Bunghara Self Sustainability Aboriginal Corporation @ MOUNT ZEIL (0872)
  ('AU-ORIC-9150','','MacDonnell','72330','oric_register_address+abs_asgs'), -- Mutitjulu Urungka Tjurpipai Aboriginal Corporation @ MUTITJULU (0872)
  ('AU-ORIC-9803','','MacDonnell','72330','oric_register_address+abs_asgs'), -- Ninti Education Aboriginal Corporation @ KINTORE (0872)
  ('AU-ORIC-10182','','Central Desert','70620','oric_register_address+abs_asgs'), -- Pmara Jutunta Aboriginal Corporation @ TI TREE (0872)
  ('AU-ORIC-10388','','MacDonnell','72330','oric_register_address+abs_asgs'), -- Taarna Arts & Culture Centre Aboriginal Corporation @ MOUNT ZEIL (0872)
  ('AU-ORIC-7406','','Central Desert','70620','oric_register_address+abs_asgs'), -- The Living Water United Pentecostal Church Yuendumu Indigenous Corporation [postal YUENDUMU; street-line Alice refused (inversion)]
  ('AU-ORIC-537','','MacDonnell','72330','oric_register_address+abs_asgs'), -- Tnorala Aboriginal Corporation @ HERMANNSBURG (0872)
  ('AU-ORIC-4039','','MacDonnell','72330','oric_register_address+abs_asgs'), -- Umalka Tjintjira Aboriginal Corporation @ IMANPA (0872)
  ('AU-ORIC-8310','','MacDonnell','72330','oric_register_address+abs_asgs'), -- Watarrka Aboriginal Corporation @ PETERMANN (0872)
  ('AU-ORIC-10155','','Central Desert','70620','oric_register_address+abs_asgs'), -- Wirliyajarrayi Pastoral Aboriginal Corporation @ WILLOWRA (0872)
  ('AU-ORIC-7120','','Central Desert','70620','oric_register_address+abs_asgs'), -- Yuendumu Magpies Football Aboriginal Corporation @ YUENDUMU (0872)
  ('AU-ABN-14158810362','','East Arnhem','71500','oric_register_address+abs_asgs'), -- Shine Out Aboriginal Corporation @ GAPUWIYAK (0880)
  ('AU-ORIC-11819','','East Arnhem','71500','oric_register_address+abs_asgs'), -- Shine Out Aboriginal Corporation @ GAPUWIYAK (0880)
  ('AU-ORIC-9582','','East Arnhem','71500','oric_register_address+abs_asgs'), -- Yarrwidi Aboriginal Corporation @ YIRRKALA (0880)
  ('AU-ORIC-8985','','Napranum','35670','own_name_town+abs_asgs'), -- Choolathah Women''s Business Indigenous Corporation @ NAPRANUM (4874)
  ('AU-ORIC-8259','','Napranum','35670','own_name_town+abs_asgs'), -- Luthik Aboriginal Corporation @ NAPRANUM (4874)
  ('AU-ORIC-7520','','Mapoon','34830','own_name_town+abs_asgs'), -- Mapoon Men''s Group Indigenous Corporation @ MAPOON (4874)
  ('AU-ORIC-2563','','Mapoon','34830','own_name_town+abs_asgs'), -- Namaleta Aboriginal Corporation @ MAPOON (4874)
  ('AU-ORIC-7769','','Napranum','35670','own_name_town+abs_asgs'), -- Napranum Men''s Group Indigenous Corporation @ NAPRANUM (4874)
  ('AU-ORIC-7465','','Weipa','37300','own_name_town+abs_asgs'), -- Sisters in Sharing Aboriginal and Torres Strait Islander Corporation @ WEIPA (4874)
  ('AU-ABN-69274417858','','Mapoon','34830','own_name_town+abs_asgs'), -- Teppethiggi Ni''Ripono Landcare Aboriginal Corporation @ MAPOON (4874)
  ('AU-ORIC-10153','','Mapoon','34830','own_name_town+abs_asgs'), -- Teppethiggi Ni''Ripono Landcare Aboriginal Corporation @ MAPOON (4874)
  ('AU-ABN-34904293061','','Mapoon','34830','own_name_town+abs_asgs'), -- Tjungundji Aboriginal Corporation @ MAPOON (4874)
  ('AU-ORIC-8458','','Mapoon','34830','own_name_town+abs_asgs'), -- Tjungundji Aboriginal Corporation @ MAPOON (4874)
  ('AU-ORIC-10355','','Mapoon','34830','own_name_town+abs_asgs'), -- Yinwum Aboriginal Corporation @ MAPOON (4874)
  ('AU-ORIC-7927','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Aragan Tribal Council (Torres Strait Islander Corporation) @ BADU ISLAND (4875)
  ('AU-ORIC-9420','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Badulgau Indigenous Corporation @ BADU ISLAND (4875)
  ('AU-ABN-60928469302','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Buai Giz Torres Strait Islander Corporation @ ERUB ISLAND (4875)
  ('AU-ORIC-10047','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Buai Giz Torres Strait Islander Corporation @ ERUB ISLAND (4875)
  ('AU-ABN-21721734225','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Dhadhin Geai Warriors & Sport''s Torres Strait Islander Corporation @ BADU ISLAND (4875)
  ('AU-ORIC-9236','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Dhadhin Geai Warriors & Sport''s Torres Strait Islander Corporation @ BADU ISLAND (4875)
  ('AU-ORIC-2216','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Dhamuway Torres Strait Islanders Corporation @ SAIBAI ISLAND (4875)
  ('AU-ORIC-9998','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Dhoengawan Torres Strait Islander Corporation @ DAUAN ISLAND (4875)
  ('AU-ORIC-2186','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Dhoeyoema Clan Torres Strait Islanders Corporation @ SAIBAI ISLAND (4875)
  ('AU-ORIC-2194','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Dowar Waier Development Torres Strait Islanders Corporation @ MER ISLAND (4875)
  ('AU-ABN-43939024319','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Garboi (Torres Strait Islanders) Corporation RNTBC @ PORUMA ISLAND (4875)
  ('AU-ORIC-4548','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Garboi (Torres Strait Islanders) Corporation RNTBC @ PORUMA ISLAND (4875)
  ('AU-ORIC-7748','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Malu Kiai - Mura Buai Fishing Torres Strait Islander Corporation @ BOIGU ISLAND (4875)
  ('AU-ORIC-7816','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Meriam Tribal Nation Secretariat Torres Strait Islander Indigenous Corporation @ MER ISLAND (4875)
  ('AU-ORIC-7361','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Op Ged Makrems Rugby League Torres Strait Islander Corporation @ MER ISLAND (4875)
  ('AU-ORIC-9896','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Port Cornwallis Fisheries (Aboriginal and Torres Strait Islander) Corporation @ DAUAN ISLAND (4875)
  ('AU-ORIC-9048','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Power of the Spirit Ministry Torres Strait Islander Corporation @ WARRABER ISLET (4875)
  ('AU-ORIC-9776','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- SURUMAU GLADIATORS FOOTBALL CLUB TORRES STRAIT ISLANDER CORPORATION @ WARRABER ISLET (4875)
  ('AU-ORIC-8188','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Saint Andrew''s Anglican Church Torres Strait Islander Corporation @ PORUMA ISLAND (4875)
  ('AU-ORIC-9341','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Thoegayn Baw Indigenous Corporation @ SAIBAI ISLAND (4875)
  ('AU-ORIC-9456','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Woesa Kula Indigenous Corporation @ DAUAN ISLAND (4875)
  ('AU-ORIC-9211','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Zion Fellowship Power of the Spirit Ministry Torres Strait Islander Corporation @ ERUB ISLAND (4875)
  ('AU-ABN-41930903077','','Pormpuraaw','36070','oric_register_address+abs_asgs'), -- Maatchangk Aboriginal Corporation @ PORMPURAAW (4892)
  ('AU-ORIC-8830','','Pormpuraaw','36070','oric_register_address+abs_asgs'), -- Maatchangk Aboriginal Corporation @ PORMPURAAW (4892)
  ('AU-ORIC-8299','','Pormpuraaw','36070','oric_register_address+abs_asgs'), -- Ngamp Raak Mela Ngamp� Agu Kuungi Aboriginal Corporation @ PORMPURAAW (4892)
  ('AU-ABN-49681356623','','Lockhart River','34570','own_name_town+abs_asgs'), -- Puuya Ngulkuma Aboriginal & Torres Strait Island Corporation @ LOCKHART RIVER (4892)
  ('AU-ORIC-10392','','Lockhart River','34570','own_name_town+abs_asgs'), -- Puuya Ngulkuma Aboriginal & Torres Strait Island Corporation @ LOCKHART RIVER (4892)
  ('AU-ORIC-8848','','Pormpuraaw','36070','oric_register_address+abs_asgs'), -- Wurrathaa Aboriginal Corporation @ PORMPURAAW (4892)
  ('AU-ORIC-7571','','Lockhart River','34570','own_name_town+abs_asgs'), -- Yelan-awu Aboriginal Corporation @ LOCKHART RIVER (4892)
  ('AU-ORIC-9971','','Hope Vale','33830','own_name_town+abs_asgs'), -- Asai Gibson Aboriginal Corporation @ HOPE VALE (4895)
  ('AU-ORIC-7768','','Hope Vale','33830','own_name_town+abs_asgs'), -- Branigan''s Aboriginal Corporation @ HOPE VALE (4895)
  ('AU-ORIC-7428','','Hope Vale','33830','own_name_town+abs_asgs'), -- Coral?s Retreat Aboriginal Corporation @ HOPE VALE (4895)
  ('AU-ABN-97963863886','','Hope Vale','33830','own_name_town+abs_asgs'), -- D.E.L.P.A Thiithaarr Warra Aboriginal Corporation @ HOPE VALE (4895)
  ('AU-ORIC-9999','','Hope Vale','33830','own_name_town+abs_asgs'), -- D.E.L.P.A Thiithaarr Warra Aboriginal Corporation @ HOPE VALE (4895)
  ('AU-ORIC-9820','','Hope Vale','33830','own_name_town+abs_asgs'), -- Jarradama Warra Western Yalanji Aboriginal Corporation @ HOPE VALE (4895)
  ('AU-ORIC-7480','','Hope Vale','33830','own_name_town+abs_asgs'), -- Juunjuwarra Aboriginal Corporation @ HOPE VALE (4895)
  ('AU-ORIC-10092','','Hope Vale','33830','own_name_town+abs_asgs'), -- MMET - Daarpa Aboriginal Corporation (Daarpa Nation) @ HOPE VALE (4895)
  ('AU-ABN-28254807963','Laverton','East Pilbara','53220','oric_register_address+abs_asgs'), -- Tjirrkarli (Aboriginal Corporation) [GIBSON DESERT NORTH per ABS; was Laverton legacy]
  ('AU-ORIC-534','Laverton','East Pilbara','53220','oric_register_address+abs_asgs') -- Tjirrkarli (Aboriginal Corporation) [GIBSON DESERT NORTH per ABS; was Laverton legacy]
),
updated AS (
  UPDATE gs_entities e
     SET lga_name = t.lga_name, lga_code = t.lga_code, lga_source = t.stamp
    FROM targets t
   WHERE e.gs_id = t.gs_id
     AND e.lga_name IS NOT DISTINCT FROM NULLIF(t.guard, '')
  RETURNING e.gs_id, t.lga_name, t.stamp
)
SELECT stamp, lga_name AS council, count(*) AS rows
  FROM updated GROUP BY 1, 2 ORDER BY 1, 3 DESC;

WITH targets(gs_id, guard, lga_name, lga_code, stamp) AS (VALUES
  ('AU-ORIC-10329','','Unincorporated NT','79399','oric_register_address+abs_asgs'), -- Anju Yinirrikun Aboriginal Corporation @ CHARLOTTE (0822)
  ('AU-ORIC-7513','','Groote Archipelago','71700','oric_register_address+abs_asgs'), -- Aruburabura Aboriginal Corporation @ ANGURUGU (0822)
  ('AU-ORIC-11813','','Litchfield','72300','oric_register_address+abs_asgs'), -- Boorooberongal Gulyangarri Aboriginal Corporation @ LLOYD CREEK (0822)
  ('AU-ORIC-7444','','Victoria Daly','74550','oric_register_address+abs_asgs'), -- Dak Milng Aboriginal Corporation @ NAUIYU (0822)
  ('AU-ABN-61377412978','','East Arnhem','71500','oric_register_address+abs_asgs'), -- Golarri Aboriginal Corporation @ GALIWINKU (0822)
  ('AU-ORIC-9849','','East Arnhem','71500','oric_register_address+abs_asgs'), -- Golarri Aboriginal Corporation @ GALIWINKU (0822)
  ('AU-ORIC-8630','','East Arnhem','71500','oric_register_address+abs_asgs'), -- Gurilka Indigenous Corporation @ GALIWINKU (0822)
  ('AU-ORIC-2498','','East Arnhem','71500','oric_register_address+abs_asgs'), -- Lanarra Homelands Aboriginal Corporation @ MILINGIMBI (0822)
  ('AU-ORIC-8393','','Roper Gulf','73600','oric_register_address+abs_asgs'), -- Magalawa Indigenous Corporation @ NUMBULWAR (0822)
  ('AU-ORIC-9858','','Tiwi Islands','74050','oric_register_address+abs_asgs'), -- Mamirnikuwi Rangers Indigenous Corporation @ PIRLANGIMPI (0822)
  ('AU-ABN-75603677183','','West Arnhem','74660','oric_register_address+abs_asgs'), -- Muburridj Aboriginal Corporation @ GUNBALANYA (0822)
  ('AU-ORIC-9641','','West Arnhem','74660','oric_register_address+abs_asgs'), -- Muburridj Aboriginal Corporation @ GUNBALANYA (0822)
  ('AU-ABN-94295724120','','West Arnhem','74660','oric_register_address+abs_asgs'), -- Namurgardabu Aboriginal Corporation @ GUNBALANYA (0822)
  ('AU-ORIC-9643','','West Arnhem','74660','oric_register_address+abs_asgs'), -- Namurgardabu Aboriginal Corporation @ GUNBALANYA (0822)
  ('AU-ABN-84802467418','','Groote Archipelago','71700','oric_register_address+abs_asgs'), -- Numayanga Aboriginal Corporation @ UMBAKUMBA (0822)
  ('AU-ORIC-2763','','Groote Archipelago','71700','oric_register_address+abs_asgs'), -- Numayanga Aboriginal Corporation @ UMBAKUMBA (0822)
  ('AU-ABN-34553639956','','Tiwi Islands','74050','oric_register_address+abs_asgs'), -- Tampu King Aboriginal Corporation @ WURRUMIYANGA (0822)
  ('AU-ORIC-9934','','Tiwi Islands','74050','oric_register_address+abs_asgs'), -- Tampu King Aboriginal Corporation @ WURRUMIYANGA (0822)
  ('AU-ORIC-11784','','Belyuen','70540','oric_register_address+abs_asgs'), -- Tjaetaba Aboriginal Corporation @ BELYUEN (0822)
  ('AU-ORIC-2668','','Victoria Daly','74550','oric_register_address+abs_asgs'), -- Camfield Mudbura Aboriginal Corporation @ VICTORIA RIVER (0852)
  ('AU-ORIC-9845','','Victoria Daly','74550','oric_register_address+abs_asgs'), -- Daguragu Community Store Aboriginal Corporation @ DAGURAGU (0852)
  ('AU-ABN-38625996362','','Victoria Daly','74550','oric_register_address+abs_asgs'), -- Djuliki Aboriginal Corporation @ TIMBER CREEK (0852)
  ('AU-ORIC-7455','','Victoria Daly','74550','oric_register_address+abs_asgs'), -- Djuliki Aboriginal Corporation @ TIMBER CREEK (0852)
  ('AU-ORIC-740','','Victoria Daly','74550','oric_register_address+abs_asgs'), -- Lingarra - Ngaringman Aboriginal Corporation @ YARRALIN (0852)
  ('AU-ABN-14781857405','','Victoria Daly','74550','oric_register_address+abs_asgs'), -- Nguwulidi Aboriginal Corporation @ TIMBER CREEK (0852)
  ('AU-ORIC-9486','','Victoria Daly','74550','oric_register_address+abs_asgs'), -- Nguwulidi Aboriginal Corporation @ TIMBER CREEK (0852)
  ('AU-ORIC-7071','','Victoria Daly','74550','oric_register_address+abs_asgs'), -- Walmoong Aboriginal Corporation @ TIMBER CREEK (0852)
  ('AU-ORIC-1556','','Central Desert','70620','oric_register_address+abs_asgs'), -- Alcoota Aboriginal Corporation @ ENGAWALA (0872)
  ('AU-ORIC-2218','','Barkly','70420','oric_register_address+abs_asgs'), -- Areyn Aboriginal Corporation @ CANTEEN CREEK (0872)
  ('AU-ORIC-9194','','Barkly','70420','oric_register_address+abs_asgs'), -- Canteen Creek Landholding Aboriginal Corporation @ CANTEEN CREEK (0872)
  ('AU-ORIC-9777','','Central Desert','70620','oric_register_address+abs_asgs'), -- Double Y Traditional Owners Association Aboriginal Corporation @ YUENDUMU (0872)
  ('AU-ABN-17317926732','','Barkly','70420','oric_register_address+abs_asgs'), -- Honeymoon Bore, akngerr-rnem akarreryel - Women?s Aboriginal Corporation @ AMPILATWATJA (0872)
  ('AU-ORIC-9159','','Barkly','70420','oric_register_address+abs_asgs'), -- Honeymoon Bore, akngerr-rnem akarreryel - Women?s Aboriginal Corporation @ AMPILATWATJA (0872)
  ('AU-ORIC-2073','','MacDonnell','72330','oric_register_address+abs_asgs'), -- Irtnwere Tyewelkere Aboriginal Corporation @ MOUNT ZEIL (0872)
  ('AU-ORIC-989','','MacDonnell','72330','oric_register_address+abs_asgs'), -- Itperlyenge Aboriginal Corporation @ HUGH (0872)
  ('AU-ORIC-988','','MacDonnell','72330','oric_register_address+abs_asgs'), -- Labrabuntja Aboriginal Corporation @ HERMANNSBURG (0872)
  ('AU-ORIC-10442','','MacDonnell','72330','oric_register_address+abs_asgs'), -- M''Bunghara Self Sustainability Aboriginal Corporation @ MOUNT ZEIL (0872)
  ('AU-ORIC-9150','','MacDonnell','72330','oric_register_address+abs_asgs'), -- Mutitjulu Urungka Tjurpipai Aboriginal Corporation @ MUTITJULU (0872)
  ('AU-ORIC-9803','','MacDonnell','72330','oric_register_address+abs_asgs'), -- Ninti Education Aboriginal Corporation @ KINTORE (0872)
  ('AU-ORIC-10182','','Central Desert','70620','oric_register_address+abs_asgs'), -- Pmara Jutunta Aboriginal Corporation @ TI TREE (0872)
  ('AU-ORIC-10388','','MacDonnell','72330','oric_register_address+abs_asgs'), -- Taarna Arts & Culture Centre Aboriginal Corporation @ MOUNT ZEIL (0872)
  ('AU-ORIC-7406','','Central Desert','70620','oric_register_address+abs_asgs'), -- The Living Water United Pentecostal Church Yuendumu Indigenous Corporation [postal YUENDUMU; street-line Alice refused (inversion)]
  ('AU-ORIC-537','','MacDonnell','72330','oric_register_address+abs_asgs'), -- Tnorala Aboriginal Corporation @ HERMANNSBURG (0872)
  ('AU-ORIC-4039','','MacDonnell','72330','oric_register_address+abs_asgs'), -- Umalka Tjintjira Aboriginal Corporation @ IMANPA (0872)
  ('AU-ORIC-8310','','MacDonnell','72330','oric_register_address+abs_asgs'), -- Watarrka Aboriginal Corporation @ PETERMANN (0872)
  ('AU-ORIC-10155','','Central Desert','70620','oric_register_address+abs_asgs'), -- Wirliyajarrayi Pastoral Aboriginal Corporation @ WILLOWRA (0872)
  ('AU-ORIC-7120','','Central Desert','70620','oric_register_address+abs_asgs'), -- Yuendumu Magpies Football Aboriginal Corporation @ YUENDUMU (0872)
  ('AU-ABN-14158810362','','East Arnhem','71500','oric_register_address+abs_asgs'), -- Shine Out Aboriginal Corporation @ GAPUWIYAK (0880)
  ('AU-ORIC-11819','','East Arnhem','71500','oric_register_address+abs_asgs'), -- Shine Out Aboriginal Corporation @ GAPUWIYAK (0880)
  ('AU-ORIC-9582','','East Arnhem','71500','oric_register_address+abs_asgs'), -- Yarrwidi Aboriginal Corporation @ YIRRKALA (0880)
  ('AU-ORIC-8985','','Napranum','35670','own_name_town+abs_asgs'), -- Choolathah Women''s Business Indigenous Corporation @ NAPRANUM (4874)
  ('AU-ORIC-8259','','Napranum','35670','own_name_town+abs_asgs'), -- Luthik Aboriginal Corporation @ NAPRANUM (4874)
  ('AU-ORIC-7520','','Mapoon','34830','own_name_town+abs_asgs'), -- Mapoon Men''s Group Indigenous Corporation @ MAPOON (4874)
  ('AU-ORIC-2563','','Mapoon','34830','own_name_town+abs_asgs'), -- Namaleta Aboriginal Corporation @ MAPOON (4874)
  ('AU-ORIC-7769','','Napranum','35670','own_name_town+abs_asgs'), -- Napranum Men''s Group Indigenous Corporation @ NAPRANUM (4874)
  ('AU-ORIC-7465','','Weipa','37300','own_name_town+abs_asgs'), -- Sisters in Sharing Aboriginal and Torres Strait Islander Corporation @ WEIPA (4874)
  ('AU-ABN-69274417858','','Mapoon','34830','own_name_town+abs_asgs'), -- Teppethiggi Ni''Ripono Landcare Aboriginal Corporation @ MAPOON (4874)
  ('AU-ORIC-10153','','Mapoon','34830','own_name_town+abs_asgs'), -- Teppethiggi Ni''Ripono Landcare Aboriginal Corporation @ MAPOON (4874)
  ('AU-ABN-34904293061','','Mapoon','34830','own_name_town+abs_asgs'), -- Tjungundji Aboriginal Corporation @ MAPOON (4874)
  ('AU-ORIC-8458','','Mapoon','34830','own_name_town+abs_asgs'), -- Tjungundji Aboriginal Corporation @ MAPOON (4874)
  ('AU-ORIC-10355','','Mapoon','34830','own_name_town+abs_asgs'), -- Yinwum Aboriginal Corporation @ MAPOON (4874)
  ('AU-ORIC-7927','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Aragan Tribal Council (Torres Strait Islander Corporation) @ BADU ISLAND (4875)
  ('AU-ORIC-9420','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Badulgau Indigenous Corporation @ BADU ISLAND (4875)
  ('AU-ABN-60928469302','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Buai Giz Torres Strait Islander Corporation @ ERUB ISLAND (4875)
  ('AU-ORIC-10047','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Buai Giz Torres Strait Islander Corporation @ ERUB ISLAND (4875)
  ('AU-ABN-21721734225','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Dhadhin Geai Warriors & Sport''s Torres Strait Islander Corporation @ BADU ISLAND (4875)
  ('AU-ORIC-9236','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Dhadhin Geai Warriors & Sport''s Torres Strait Islander Corporation @ BADU ISLAND (4875)
  ('AU-ORIC-2216','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Dhamuway Torres Strait Islanders Corporation @ SAIBAI ISLAND (4875)
  ('AU-ORIC-9998','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Dhoengawan Torres Strait Islander Corporation @ DAUAN ISLAND (4875)
  ('AU-ORIC-2186','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Dhoeyoema Clan Torres Strait Islanders Corporation @ SAIBAI ISLAND (4875)
  ('AU-ORIC-2194','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Dowar Waier Development Torres Strait Islanders Corporation @ MER ISLAND (4875)
  ('AU-ABN-43939024319','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Garboi (Torres Strait Islanders) Corporation RNTBC @ PORUMA ISLAND (4875)
  ('AU-ORIC-4548','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Garboi (Torres Strait Islanders) Corporation RNTBC @ PORUMA ISLAND (4875)
  ('AU-ORIC-7748','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Malu Kiai - Mura Buai Fishing Torres Strait Islander Corporation @ BOIGU ISLAND (4875)
  ('AU-ORIC-7816','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Meriam Tribal Nation Secretariat Torres Strait Islander Indigenous Corporation @ MER ISLAND (4875)
  ('AU-ORIC-7361','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Op Ged Makrems Rugby League Torres Strait Islander Corporation @ MER ISLAND (4875)
  ('AU-ORIC-9896','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Port Cornwallis Fisheries (Aboriginal and Torres Strait Islander) Corporation @ DAUAN ISLAND (4875)
  ('AU-ORIC-9048','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Power of the Spirit Ministry Torres Strait Islander Corporation @ WARRABER ISLET (4875)
  ('AU-ORIC-9776','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- SURUMAU GLADIATORS FOOTBALL CLUB TORRES STRAIT ISLANDER CORPORATION @ WARRABER ISLET (4875)
  ('AU-ORIC-8188','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Saint Andrew''s Anglican Church Torres Strait Islander Corporation @ PORUMA ISLAND (4875)
  ('AU-ORIC-9341','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Thoegayn Baw Indigenous Corporation @ SAIBAI ISLAND (4875)
  ('AU-ORIC-9456','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Woesa Kula Indigenous Corporation @ DAUAN ISLAND (4875)
  ('AU-ORIC-9211','','Torres Strait Island','36960','oric_register_address+abs_asgs'), -- Zion Fellowship Power of the Spirit Ministry Torres Strait Islander Corporation @ ERUB ISLAND (4875)
  ('AU-ABN-41930903077','','Pormpuraaw','36070','oric_register_address+abs_asgs'), -- Maatchangk Aboriginal Corporation @ PORMPURAAW (4892)
  ('AU-ORIC-8830','','Pormpuraaw','36070','oric_register_address+abs_asgs'), -- Maatchangk Aboriginal Corporation @ PORMPURAAW (4892)
  ('AU-ORIC-8299','','Pormpuraaw','36070','oric_register_address+abs_asgs'), -- Ngamp Raak Mela Ngamp� Agu Kuungi Aboriginal Corporation @ PORMPURAAW (4892)
  ('AU-ABN-49681356623','','Lockhart River','34570','own_name_town+abs_asgs'), -- Puuya Ngulkuma Aboriginal & Torres Strait Island Corporation @ LOCKHART RIVER (4892)
  ('AU-ORIC-10392','','Lockhart River','34570','own_name_town+abs_asgs'), -- Puuya Ngulkuma Aboriginal & Torres Strait Island Corporation @ LOCKHART RIVER (4892)
  ('AU-ORIC-8848','','Pormpuraaw','36070','oric_register_address+abs_asgs'), -- Wurrathaa Aboriginal Corporation @ PORMPURAAW (4892)
  ('AU-ORIC-7571','','Lockhart River','34570','own_name_town+abs_asgs'), -- Yelan-awu Aboriginal Corporation @ LOCKHART RIVER (4892)
  ('AU-ORIC-9971','','Hope Vale','33830','own_name_town+abs_asgs'), -- Asai Gibson Aboriginal Corporation @ HOPE VALE (4895)
  ('AU-ORIC-7768','','Hope Vale','33830','own_name_town+abs_asgs'), -- Branigan''s Aboriginal Corporation @ HOPE VALE (4895)
  ('AU-ORIC-7428','','Hope Vale','33830','own_name_town+abs_asgs'), -- Coral?s Retreat Aboriginal Corporation @ HOPE VALE (4895)
  ('AU-ABN-97963863886','','Hope Vale','33830','own_name_town+abs_asgs'), -- D.E.L.P.A Thiithaarr Warra Aboriginal Corporation @ HOPE VALE (4895)
  ('AU-ORIC-9999','','Hope Vale','33830','own_name_town+abs_asgs'), -- D.E.L.P.A Thiithaarr Warra Aboriginal Corporation @ HOPE VALE (4895)
  ('AU-ORIC-9820','','Hope Vale','33830','own_name_town+abs_asgs'), -- Jarradama Warra Western Yalanji Aboriginal Corporation @ HOPE VALE (4895)
  ('AU-ORIC-7480','','Hope Vale','33830','own_name_town+abs_asgs'), -- Juunjuwarra Aboriginal Corporation @ HOPE VALE (4895)
  ('AU-ORIC-10092','','Hope Vale','33830','own_name_town+abs_asgs'), -- MMET - Daarpa Aboriginal Corporation (Daarpa Nation) @ HOPE VALE (4895)
  ('AU-ABN-28254807963','Laverton','East Pilbara','53220','oric_register_address+abs_asgs'), -- Tjirrkarli (Aboriginal Corporation) [GIBSON DESERT NORTH per ABS; was Laverton legacy]
  ('AU-ORIC-534','Laverton','East Pilbara','53220','oric_register_address+abs_asgs') -- Tjirrkarli (Aboriginal Corporation) [GIBSON DESERT NORTH per ABS; was Laverton legacy]
)
SELECT t.gs_id, e.canonical_name, COALESCE(e.lga_name,'(unplaced)') AS current_lga
  FROM targets t
  JOIN gs_entities e ON e.gs_id = t.gs_id
 WHERE e.lga_source IS DISTINCT FROM t.stamp OR e.lga_name IS DISTINCT FROM t.lga_name;
