// Goods impact film data. Every number is sourced. Refresh monthly.
//
// GENERATED by scripts/build-goods-impact-data.mjs. Edit that script, not this file.
//   need / gap: goods_communities priority in (active, lead) (the curated slice).
//   footprint: Goods Asset Register canon checked 2026-07-25.
//   washers: manual in-community ruling; not derived from register rows.
//   communities: goods_communities, priority in (active, lead), top by demand_beds.
//
// To refresh: node --env-file=.env scripts/build-goods-impact-data.mjs

export type GoodsImpactData = {
  generatedAt: string;
  footprintAsOf: string;
  need: { beds: number; washers: number; communities: number };
  delivered: { beds: number; washers: number };
  gap: { beds: number; washers: number };
  communities: { name: string; state: string; beds: number }[];
};

export const goodsImpactData: GoodsImpactData = {
  generatedAt: '2026-05-28',
  footprintAsOf: '2026-07-25',
  need: { beds: 12504, washers: 1563, communities: 64 },
  delivered: { beds: 540, washers: 22 },
  gap: { beds: 11964, washers: 1541 },
  communities: [
    { name: "Maningrida", state: "NT", beds: 930 },
    { name: "Wadeye", state: "NT", beds: 918 },
    { name: "Galiwinku", state: "NT", beds: 841 },
    { name: "Wurrumiyanga", state: "NT", beds: 630 },
    { name: "Milingimbi", state: "NT", beds: 493 },
    { name: "Ngukurr", state: "NT", beds: 463 },
    { name: "Gunbalanya", state: "NT", beds: 450 },
    { name: "Gapuwiyak", state: "NT", beds: 372 },
  ],
};
