-- GENERATED by scripts/sync-goods-governance-roster.mjs — do not edit by hand.
-- Generated: 2026-06-09T07:50:52.883Z
-- Source: act-global-infrastructure/wiki/decisions/goods-governance-roster.md
-- Idempotent + additive: INSERT-WHERE-NOT-EXISTS + UPDATE, matched on
--   (org_profile_id, project_id, lower(name), contact_type='governance').
-- These rows are CO-OWNERS (governance), never laddered. See the wiki roster.

BEGIN;

-- Kristy Bloomfield
INSERT INTO org_contacts (id, org_profile_id, project_id, name, role, organisation, contact_type, linkedin_url, notes, created_at, updated_at)
SELECT gen_random_uuid(), '8b6160a1-7eea-4bd2-8404-71c196381de0'::uuid, '01359765-a88c-4ac2-8e4d-c40beb01c299'::uuid, 'Kristy Bloomfield', 'Director (co-owner)', 'The Butterfly Movement Ltd', 'governance', NULL, 'Status: continuing
Context: Central Arrernte, Eastern Arrernte, and Alyawarra woman; Traditional Owner of Mparntwe (Alice Springs); co-director of Oonchiumpa
Co-owner of Goods governance (The Butterfly Movement Ltd board). Never laddered per OCAP. Synced from wiki/decisions/goods-governance-roster.md.', now(), now()
WHERE NOT EXISTS (SELECT 1 FROM org_contacts WHERE org_profile_id = '8b6160a1-7eea-4bd2-8404-71c196381de0'::uuid AND project_id = '01359765-a88c-4ac2-8e4d-c40beb01c299'::uuid AND lower(name) = lower('Kristy Bloomfield') AND contact_type = 'governance');
UPDATE org_contacts SET
  role = 'Director (co-owner)', organisation = 'The Butterfly Movement Ltd', contact_type = 'governance',
  linkedin_url = COALESCE(NULL, linkedin_url), notes = 'Status: continuing
Context: Central Arrernte, Eastern Arrernte, and Alyawarra woman; Traditional Owner of Mparntwe (Alice Springs); co-director of Oonchiumpa
Co-owner of Goods governance (The Butterfly Movement Ltd board). Never laddered per OCAP. Synced from wiki/decisions/goods-governance-roster.md.', updated_at = now()
WHERE org_profile_id = '8b6160a1-7eea-4bd2-8404-71c196381de0'::uuid AND project_id = '01359765-a88c-4ac2-8e4d-c40beb01c299'::uuid AND lower(name) = lower('Kristy Bloomfield') AND contact_type = 'governance';

-- Audrey Deemal
INSERT INTO org_contacts (id, org_profile_id, project_id, name, role, organisation, contact_type, linkedin_url, notes, created_at, updated_at)
SELECT gen_random_uuid(), '8b6160a1-7eea-4bd2-8404-71c196381de0'::uuid, '01359765-a88c-4ac2-8e4d-c40beb01c299'::uuid, 'Audrey Deemal', 'Director (co-owner)', 'The Butterfly Movement Ltd', 'governance', NULL, 'Status: continuing
Co-owner of Goods governance (The Butterfly Movement Ltd board). Never laddered per OCAP. Synced from wiki/decisions/goods-governance-roster.md.', now(), now()
WHERE NOT EXISTS (SELECT 1 FROM org_contacts WHERE org_profile_id = '8b6160a1-7eea-4bd2-8404-71c196381de0'::uuid AND project_id = '01359765-a88c-4ac2-8e4d-c40beb01c299'::uuid AND lower(name) = lower('Audrey Deemal') AND contact_type = 'governance');
UPDATE org_contacts SET
  role = 'Director (co-owner)', organisation = 'The Butterfly Movement Ltd', contact_type = 'governance',
  linkedin_url = COALESCE(NULL, linkedin_url), notes = 'Status: continuing
Co-owner of Goods governance (The Butterfly Movement Ltd board). Never laddered per OCAP. Synced from wiki/decisions/goods-governance-roster.md.', updated_at = now()
WHERE org_profile_id = '8b6160a1-7eea-4bd2-8404-71c196381de0'::uuid AND project_id = '01359765-a88c-4ac2-8e4d-c40beb01c299'::uuid AND lower(name) = lower('Audrey Deemal') AND contact_type = 'governance';

-- Sonia
INSERT INTO org_contacts (id, org_profile_id, project_id, name, role, organisation, contact_type, linkedin_url, notes, created_at, updated_at)
SELECT gen_random_uuid(), '8b6160a1-7eea-4bd2-8404-71c196381de0'::uuid, '01359765-a88c-4ac2-8e4d-c40beb01c299'::uuid, 'Sonia', 'Transition director', 'The Butterfly Movement Ltd', 'governance', NULL, 'Status: transitioning (handover 26 Jun 2026)
Co-owner of Goods governance (The Butterfly Movement Ltd board). Never laddered per OCAP. Synced from wiki/decisions/goods-governance-roster.md.', now(), now()
WHERE NOT EXISTS (SELECT 1 FROM org_contacts WHERE org_profile_id = '8b6160a1-7eea-4bd2-8404-71c196381de0'::uuid AND project_id = '01359765-a88c-4ac2-8e4d-c40beb01c299'::uuid AND lower(name) = lower('Sonia') AND contact_type = 'governance');
UPDATE org_contacts SET
  role = 'Transition director', organisation = 'The Butterfly Movement Ltd', contact_type = 'governance',
  linkedin_url = COALESCE(NULL, linkedin_url), notes = 'Status: transitioning (handover 26 Jun 2026)
Co-owner of Goods governance (The Butterfly Movement Ltd board). Never laddered per OCAP. Synced from wiki/decisions/goods-governance-roster.md.', updated_at = now()
WHERE org_profile_id = '8b6160a1-7eea-4bd2-8404-71c196381de0'::uuid AND project_id = '01359765-a88c-4ac2-8e4d-c40beb01c299'::uuid AND lower(name) = lower('Sonia') AND contact_type = 'governance';

COMMIT;
