import type {
  MatchedGrant,
  OrgContactWithEntity,
  OrgPipelineItemWithEntity,
  OrgProjectSummary,
} from '@/lib/services/org-dashboard-service';
import type { WikiSupportFrontierQueue } from '@/lib/services/wiki-support-frontier';
import type { ActFunderIntelligence } from '@/lib/services/act-funder-intelligence';
import type { ActRelationshipLedger } from '@/lib/services/act-relationship-ledger';
import type { ActOpportunityContextStatus } from '@/lib/services/act-opportunity-context';

export const ACT_E2E_PROJECTS: OrgProjectSummary[] = [
  {
    id: 'e2e-goods',
    org_profile_id: 'act-fast-local',
    parent_project_id: null,
    name: 'Goods on Country',
    slug: 'goods',
    code: 'ACT-GD',
    description: 'Essential goods, circular materials, and community-led procurement.',
    tier: 'major',
    category: 'enterprise',
    status: 'active',
    sort_order: 1,
    abn: null,
    linked_gs_entity_id: null,
    logo_url: null,
    metadata: {},
    updated_at: '2026-07-10T09:00:00.000Z',
    program_count: 2,
    pipeline_count: 1,
    contact_count: 1,
    pipeline_value: 1_200_000,
    children: [],
  },
];

export const ACT_E2E_PIPELINE: OrgPipelineItemWithEntity[] = [
  {
    id: 'e2e-real-eoi',
    project_id: 'e2e-goods',
    name: 'REAL Innovation Fund EOI',
    amount_display: '$1.2M',
    amount_numeric: 1_200_000,
    funder: 'Snow Foundation',
    deadline: null,
    status: 'submitted',
    grant_opportunity_id: null,
    notes: 'EOI submitted; agree the relationship follow-up and evidence owner.',
    funder_entity_id: null,
    funder_type: 'foundation',
    source_type: 'grant',
    source_ref: 'e2e-real-eoi',
    pathway: 'foundation',
    recommended_role: 'partner',
    project_code: 'ACT-GD',
    owner_name: null,
    next_action: null,
    next_action_at: null,
    created_at: '2026-07-08T04:00:00.000Z',
    updated_at: '2026-07-10T09:00:00.000Z',
    funder_entity_gs_id: null,
    funder_entity_name: null,
    grant_url: null,
    grant_name: null,
    grant_provider: null,
  },
];

export const ACT_E2E_CONTACTS: OrgContactWithEntity[] = [
  {
    id: 'e2e-snow-contact',
    name: 'Alex Snow',
    role: 'Philanthropy partner',
    organisation: 'Snow Foundation',
    contact_type: 'funder',
    email: 'alex@example.test',
    phone: null,
    notes: 'Warm relationship path for Goods on Country.',
    last_contacted_at: '2026-07-08T03:00:00.000Z',
    linked_entity_id: null,
    linkedin_url: null,
    person_id: null,
    updated_at: '2026-07-10T09:00:00.000Z',
    source_system: 'ghl',
    source_label: 'HighLevel pilot fixture',
    linked_entity_gs_id: null,
    linked_entity_name: 'Snow Foundation',
    linked_entity_type: 'foundation',
    linked_entity_abn: null,
    ghl_contact_id: 'e2e-ghl-snow',
    ghl_engagement_status: 'warm',
    ghl_last_contact_date: '2026-07-08T03:00:00.000Z',
    notion_id: null,
    unified_tags: ['role:funder', 'project:ACT-GD', 'warm', 'source:gmail'],
  },
];

export const ACT_E2E_MATCHED_GRANTS: MatchedGrant[] = [
  {
    id: 'e2e-goods-grant',
    name: 'Regional Circular Economy Partnership',
    description: 'Supports First Nations-led circular economy infrastructure and regional delivery partnerships.',
    amount_min: 250_000,
    amount_max: 1_000_000,
    deadline: null,
    closes_at: null,
    provider: 'Snow Foundation',
    categories: ['Goods on Country'],
    focus_areas: ['First Nations', 'circular economy', 'regional communities'],
    url: '/grants/e2e-goods-grant',
    fit_score: 92,
  },
];

export const ACT_E2E_FRONTIER: WikiSupportFrontierQueue = {
  total: 0,
  rows: [],
  by_route: [],
};

export const ACT_E2E_OPPORTUNITY_CONTEXT: ActOpportunityContextStatus = {
  generatedAt: '2026-07-14T01:00:00.000Z',
  overallStatus: 'ok',
  summary: '7/7 sources current. Discovery activity is ready for review.',
  metrics: {
    openGrants: 1,
    grantsDue30d: 1,
    grantsUpdated7d: 1,
    relationshipRows: 2,
    recentRelationshipTouches: 1,
    funderSnapshots: 1,
    opportunityDecisions: 1,
    sourceIssues: 0,
  },
  sources: [],
  nextSteps: [],
  discoveryReceipt: {
    batchWindowMinutes: 5,
    latestAt: '2026-07-14T01:00:00.000Z',
    newSignals: 2,
    changedSignals: 1,
    opportunitySignals: 1,
    relationshipSignals: 1,
    refreshedPrograms: 1,
  },
  recentEvents: [
    {
      id: 'e2e-discovery-opportunity',
      sourceSystem: 'gmail',
      sourceType: 'email',
      sourceRef: 'e2e-discovery-message',
      sourceUrl: '/grants/e2e-goods-grant',
      title: 'New Goods partnership round',
      summary: 'A verified regional partnership round needs an ACT project decision.',
      actorName: 'Program team',
      actorEmail: null,
      organisation: 'Regional Partnership Fund',
      lane: 'grant',
      signalKind: 'open_opportunity',
      confidence: 0.94,
      happenedAt: '2026-07-14T00:30:00.000Z',
      createdAt: '2026-07-14T00:40:00.000Z',
      updatedAt: '2026-07-14T00:40:00.000Z',
      discoveryState: 'new',
      metadata: {
        project: 'Goods on Country',
        project_code: 'ACT-GD',
        score: 92,
        deadline: '2026-08-16',
        amount: '$180,000',
        readiness: 'prepare application evidence',
        recommended_move: 'Build the eligibility evidence pack before drafting.',
        next_touch: 'Confirm eligibility evidence and project ownership.',
        evidence_gaps: ['eligibility evidence'],
      },
    },
  ],
};

export const ACT_E2E_RELATIONSHIP_LEDGER: ActRelationshipLedger = {
  generatedAt: '2026-07-13T08:00:00.000Z',
  summary: {
    organisations: 3,
    invoices: 3,
    paidInvoices: 2,
    receivedTotal: 182_000,
    outstandingInvoices: 1,
    outstandingTotal: 16_500,
    repeatRelationships: 0,
    withConversationEvidence: 2,
    contributions: 1,
    unpaidContributions: 0,
    suggestedContributions: 2,
    plannedFollowUps: 1,
    overdueFollowUps: 1,
  },
  suggestions: [
    {
      id: 'e2e-suggest-lgant-intro',
      source: 'gmail',
      organisation: 'Local Government Association of the Northern Territory',
      person: 'Michelle VanZanden',
      title: 'LGANT Circular Economy Symposium and CDU intro',
      summary: 'LGANT offered to introduce ACT to CDU about remote textiles and community infrastructure.',
      happenedAt: '2026-07-09T02:39:35.000Z',
      direction: 'received',
      kind: 'introduction',
      payment: 'not_expected',
      reason: 'A named introduction or connection was found.',
    },
    {
      id: 'e2e-suggest-artlands-invite',
      source: 'gmail',
      organisation: 'Regional Arts Australia / Artlands',
      person: 'Skye Parker',
      title: 'Artlands 2026 Witta meeting invitation',
      summary: 'Skye wants to visit Witta and yarn with ACT, creating a regional arts invitation pathway.',
      happenedAt: '2026-07-08T04:25:03.000Z',
      direction: 'received',
      kind: 'event',
      payment: 'not_expected',
      reason: 'A direct invitation into an event or place was found.',
    },
  ],
  items: [
    {
      key: 'regional arts australia',
      organisation: 'Regional Arts Australia',
      balance: 'awaiting_payment',
      invoicedTotal: 148_500,
      receivedTotal: 132_000,
      outstandingTotal: 16_500,
      actPaidThemTotal: 0,
      paidInvoiceCount: 1,
      outstandingInvoiceCount: 1,
      invoiceCount: 2,
      oldestOverdueDays: 13,
      firstInvoiceAt: '2026-03-01',
      lastInvoiceAt: '2026-06-30',
      lastPaidAt: '2026-04-01',
      lastContactAt: '2026-07-08T04:25:03.000Z',
      projectCodes: ['ACT-HV'],
      work: ['Radical Scoops regional arts collaboration and host organisation engagement.'],
      nextMove: 'Confirm payment and the relationship next step; the oldest invoice is 13 days overdue.',
      evidenceGaps: ['unbilled or freely contributed work is not yet captured'],
      people: [{ id: 'e2e-skye', name: 'Skye Parker', email: 'skye@example.test', role: 'Event producer', source: 'gmail', lastContactAt: '2026-07-08T04:25:03.000Z' }],
      conversations: [{ id: 'e2e-artlands', source: 'gmail', title: 'Artlands 2026 Witta meeting invitation', summary: 'Skye wants to visit Witta and yarn with ACT.', person: 'Skye Parker', happenedAt: '2026-07-08T04:25:03.000Z' }],
      contributions: [],
      followUp: null,
      invoices: [
        { id: 'e2e-invoice-due', number: 'INV-0337', status: 'AUTHORISED', date: '2026-06-30', dueDate: '2026-07-30', fullyPaidDate: null, total: 16_500, paid: 0, due: 16_500, daysOverdue: 13, projectCode: 'ACT-HV', reference: 'Radical Scoops', work: ['Radical Scoops regional arts collaboration.'] },
        { id: 'e2e-invoice-paid', number: 'INV-0300', status: 'PAID', date: '2026-03-01', dueDate: '2026-03-31', fullyPaidDate: '2026-04-01', total: 132_000, paid: 132_000, due: 0, daysOverdue: 0, projectCode: 'ACT-HV', reference: 'Regional arts delivery', work: ['Regional arts delivery.'] },
      ],
    },
    {
      key: 'country arts network',
      organisation: 'Country Arts Network',
      balance: 'exchange_only',
      invoicedTotal: 0,
      receivedTotal: 0,
      outstandingTotal: 0,
      actPaidThemTotal: 0,
      paidInvoiceCount: 0,
      outstandingInvoiceCount: 0,
      invoiceCount: 0,
      oldestOverdueDays: 0,
      firstInvoiceAt: null,
      lastInvoiceAt: null,
      lastPaidAt: null,
      lastContactAt: '2026-07-02T03:00:00.000Z',
      projectCodes: [],
      work: [],
      nextMove: 'Acknowledge what they contributed and agree on the most natural way to keep the relationship reciprocal.',
      evidenceGaps: ['named relationship owner', 'conversation history'],
      people: [],
      conversations: [],
      contributions: [{
        id: 'e2e-country-arts-space',
        direction: 'received',
        kind: 'space',
        summary: 'Provided venue space for a community arts gathering.',
        payment: 'not_expected',
        amount: null,
        person: 'Morgan Lee',
        happenedAt: '2026-07-02T03:00:00.000Z',
      }],
      followUp: {
        id: 'e2e-country-arts-follow-up',
        action: 'Thank Morgan for the venue support and agree the next gathering step.',
        owner: 'Benjamin',
        dueAt: '2026-07-12',
        status: 'planned',
        completedAt: null,
      },
      invoices: [],
    },
    {
      key: 'snow foundation',
      organisation: 'Snow Foundation',
      balance: 'paid_once',
      invoicedTotal: 50_000,
      receivedTotal: 50_000,
      outstandingTotal: 0,
      actPaidThemTotal: 0,
      paidInvoiceCount: 1,
      outstandingInvoiceCount: 0,
      invoiceCount: 1,
      oldestOverdueDays: 0,
      firstInvoiceAt: '2025-08-01',
      lastInvoiceAt: '2025-08-01',
      lastPaidAt: '2025-08-20',
      lastContactAt: '2026-07-08T03:00:00.000Z',
      projectCodes: ['ACT-GD'],
      work: ['Goods on Country evidence, community-led delivery planning, and supporter reporting.'],
      nextMove: 'Ask Alex for an evidence call and connect the current Goods on Country case to Snow Foundation priorities.',
      evidenceGaps: ['the outcome of the latest Goods on Country conversation'],
      people: [{ id: 'e2e-snow-ledger-person', name: 'Alex Snow', email: 'alex@example.test', role: 'Philanthropy partner', source: 'gmail', lastContactAt: '2026-07-08T03:00:00.000Z' }],
      conversations: [{ id: 'e2e-snow-ledger-conversation', source: 'gmail', title: 'Goods on Country evidence conversation', summary: 'Alex confirmed interest in an evidence conversation.', person: 'Alex Snow', happenedAt: '2026-07-08T03:00:00.000Z' }],
      contributions: [],
      followUp: null,
      invoices: [
        { id: 'e2e-snow-invoice', number: 'INV-0241', status: 'PAID', date: '2025-08-01', dueDate: '2025-08-15', fullyPaidDate: '2025-08-20', total: 50_000, paid: 50_000, due: 0, daysOverdue: 0, projectCode: 'ACT-GD', reference: 'Goods on Country', work: ['Goods on Country evidence and delivery planning.'] },
      ],
    },
  ],
};

export const ACT_E2E_FUNDER_INTELLIGENCE: ActFunderIntelligence = {
  generatedAt: '2026-07-10T09:00:00.000Z',
  summary: {
    candidates: 1,
    active: 1,
    withContacts: 1,
    withFundingHistory: 1,
    withNamedPeople: 1,
    withWarmPath: 1,
    needingEnrichment: 0,
  },
  globalCoverage: {
    foundations: 11_111,
    websites: 1,
    descriptions: 1,
    focusAreas: 1,
    scrapedSources: 2,
    granteeRows: 2,
    foundationPeople: 1,
    boardRoles: 1,
    ghlContacts: 1,
    gmailMessages: 1,
    notionOrganisations: 0,
  },
  sourceAudit: [
    {
      key: 'foundation_profiles',
      label: 'Foundation profiles',
      count: 1,
      covered: 1,
      total: 1,
      status: 'strong',
      latestAt: '2026-07-10T09:00:00.000Z',
      detail: 'Website, focus, giving, and application context.',
    },
    {
      key: 'relationship_context',
      label: 'Relationship context',
      count: 2,
      covered: 1,
      total: 1,
      status: 'strong',
      latestAt: '2026-07-08T03:00:00.000Z',
      detail: 'HighLevel and Gmail evidence connected to the funder.',
    },
  ],
  contactResolution: {
    total: 1,
    suggested: 1,
    ambiguous: 0,
    research: 0,
    items: [
      {
        contactId: 'e2e-unlinked-contact',
        name: 'Regional Partner',
        organisation: 'Regional Partner Foundation',
        email: 'hello@regionalpartner.example',
        status: 'suggested',
        candidates: [
          {
            entityId: 'e2e-regional-partner-entity',
            name: 'Regional Partner Foundation Limited',
            abn: '12345678901',
            entityType: 'foundation',
            website: 'https://regionalpartner.example',
            nameScore: 91,
          },
        ],
      },
    ],
  },
  dossiers: [
    {
      foundationId: 'e2e-snow-contact',
      relationshipRecordId: 'e2e-snow-relationship',
      projectId: 'e2e-goods',
      entityId: 'e2e-snow-entity',
      name: 'Snow Foundation',
      abn: '13003263930',
      website: 'https://www.snowfoundation.org.au',
      description: 'A family foundation backing community-led responses and long-term systems change.',
      annualGiving: 10_000_000,
      thematicFocus: ['First Nations', 'community development', 'social justice'],
      geographicFocus: ['Australia', 'regional communities'],
      targetRecipients: ['community-controlled organisations'],
      givingPhilosophy: 'Back trusted community partners and learn with them over time.',
      applicationTips: 'Start with a relationship and a clear account of community leadership.',
      sourceUrls: ['https://www.snowfoundation.org.au'],
      enrichedAt: '2026-07-10T09:00:00.000Z',
      projects: ['Goods on Country'],
      stages: ['submitted'],
      engagementStatuses: ['active'],
      fitScore: 92,
      active: true,
      nextStep: 'Ask Alex for an evidence call.',
      nextTouchAt: '2026-07-20T02:00:00.000Z',
      lastInteractionAt: '2026-07-08T03:00:00.000Z',
      relationshipState: 'warm',
      relationshipScore: 82,
      evidenceScore: 88,
      recommendedAction: 'Ask Alex Snow for a 30 minute evidence call about Goods on Country.',
      whyNow: 'A live EOI and recent warm contact create a specific reason to talk now.',
      evidenceGaps: [],
      granteeCount: 2,
      granteeAmount: 350_000,
      latestGrantYear: 2025,
      programCount: 1,
      openProgramCount: 1,
      applicationPathCount: 1,
      annualReportYears: 2,
      latestReportYear: 2025,
      boardRoleCount: 1,
      pipelineCount: 1,
      people: [
        {
          id: 'e2e-snow-person',
          name: 'Alex Snow',
          email: 'alex@example.test',
          role: 'Philanthropy partner',
          organisation: 'Snow Foundation',
          source: 'ghl',
          lastContactAt: '2026-07-08T03:00:00.000Z',
          evidence: 'Warm relationship path recorded against the Goods on Country EOI.',
          confidence: 'high',
        },
      ],
      grantees: [
        {
          id: 'e2e-grantee-one',
          name: 'Regional community partner',
          amount: 200_000,
          year: 2025,
          program: 'Community-led change',
          sourceUrl: 'https://www.snowfoundation.org.au',
          confidence: 'high',
        },
      ],
      programs: [
        {
          id: 'e2e-program-one',
          name: 'Community-led partnerships',
          status: 'open',
          deadline: null,
          amountMin: null,
          amountMax: null,
          applicationProcess: 'Begin with a relationship conversation.',
          applicationMode: 'relationship-led',
          url: 'https://www.snowfoundation.org.au',
          sourceCount: 2,
        },
      ],
      interactions: [
        {
          id: 'e2e-interaction-one',
          type: 'email',
          summary: 'Alex confirmed interest in an evidence conversation.',
          notes: null,
          happenedAt: '2026-07-08T03:00:00.000Z',
          status: 'approached',
        },
      ],
      paths: [
        {
          id: 'e2e-path-one',
          kind: 'direct_contact',
          label: 'Alex Snow',
          detail: 'Recent HighLevel contact linked to Snow Foundation and Goods on Country.',
          strength: 90,
          sourceUrl: null,
          verified: true,
        },
      ],
      sourceAudit: [
        {
          key: 'profile',
          label: 'Profile and focus',
          count: 1,
          covered: 1,
          total: 1,
          status: 'strong',
          latestAt: '2026-07-10T09:00:00.000Z',
          detail: 'Website, focus, and application evidence available.',
        },
        {
          key: 'people',
          label: 'People and contact',
          count: 1,
          covered: 1,
          total: 1,
          status: 'strong',
          latestAt: '2026-07-08T03:00:00.000Z',
          detail: 'One recent named relationship.',
        },
      ],
    },
  ],
};
