// The QBE Catalysing Impact volunteer team's buyer map for Goods on Country (deliverable dated
// September 2026, thoughts/shared/drafts/Goods_on_Country_DELIVERABLE.xlsx, BUYER MAP sheet).
// Their judgement, kept as data: what role each organisation could play in the community-enterprise
// model, who would pay, and how it would buy. Evidence notes and quantities are left out on purpose:
// the sales figures conflict with the Goods canon and must go through /reconcile first. Owners'
// names are left out too.
//
// gsId links to gs_entities. match says how: exact (same name), legal-name (the registered name of
// the same organisation), check (more than one candidate, or the name differs; Ben to confirm),
// none (a group or a programme, not one organisation).

export type QbeRegion = 'Central Desert & Barkly' | 'North East Arnhem Land' | 'Kimberley' | 'Cape York & Palm Island' | 'Remote South Australia' | 'Cross-region';
export type ModelRole = 'seller' | 'channel' | 'buyer' | 'funder' | 'referrer' | 'connector' | 'producer';

export interface QbeBuyer {
  region: QbeRegion;
  name: string;
  orgType: string | null;
  /** The team's own words for the role. */
  role: string | null;
  /** The same role read onto the Goods model's boxes. */
  modelRoles: ModelRole[];
  purchaseStatus: string | null;
  evidenceStatus: string | null;
  payerRoute: string | null;
  pathway: string | null;
  priority: number | null;
  nextQuestion: string | null;
  sourceUrl: string | null;
  gsId: string | null;
  match: 'exact' | 'legal-name' | 'check' | 'none';
}

export const QBE_REGIONS: readonly QbeRegion[] = ['Central Desert & Barkly', 'North East Arnhem Land', 'Kimberley', 'Cape York & Palm Island', 'Remote South Australia', 'Cross-region'];

export const QBE_BUYER_MAP: readonly QbeBuyer[] = [
  { region: "Central Desert & Barkly", name: "Oonchiumpa Consultancy and Services", orgType: "Aboriginal community-controlled organisation",
    role: "Community seller / production partner", modelRoles: ["seller", "producer"],
    purchaseStatus: "Relationship, not confirmed buyer", evidenceStatus: "Confirmed relationship",
    payerRoute: "Community enterprise revenue / purchaser funds", pathway: "Stock arrangement, local selling, invoicing and fulfilment to be agreed",
    priority: 1, nextQuestion: "Will Oonchiumpa hold stock, invoice customers and manage warranty/reorders?",
    sourceUrl: "https://www.oonchiumpa.com.au/", gsId: "AU-ABN-53658668627", match: 'legal-name' },
  { region: "Central Desert & Barkly", name: "Centrecorp Foundation", orgType: "Foundation / community-benefit funder",
    role: "Institutional buyer / funder", modelRoles: ["buyer", "funder"],
    purchaseStatus: "Confirmed buyer", evidenceStatus: "Confirmed purchase",
    payerRoute: "Foundation / community-benefit funding", pathway: "Request or project need → approval → quote/invoice → delivery",
    priority: 1, nextQuestion: "Confirm paid quantity against website/PPT conflicts, budget route, approval and status of repeat order.",
    sourceUrl: "https://www.goodsoncountry.com/partners/centrecorp", gsId: "AU-ABN-31136052796", match: 'exact' },
  { region: "Central Desert & Barkly", name: "Community Housing Central Australia", orgType: "Community housing provider",
    role: "Institutional housing customer", modelRoles: ["buyer"],
    purchaseStatus: "Potential buyer", evidenceStatus: "Potential",
    payerRoute: "Housing / supported accommodation budgets", pathway: "Need → budget delegation → supplier quote/onboarding → order",
    priority: 1, nextQuestion: "Does CHCA buy beds, and are furnishings eligible in vacancy or supported-housing budgets?",
    sourceUrl: "https://www.chca.org.au/", gsId: null, match: 'none' },
  { region: "Central Desert & Barkly", name: "Central Land Council community-development programs", orgType: "Land council / royalty community-development",
    role: "Royalty-funded customer / connector", modelRoles: ["buyer", "funder", "connector"],
    purchaseStatus: "Potential funder", evidenceStatus: "Potential",
    payerRoute: "Royalty / rent / compensation community-benefit funds", pathway: "Community proposal → governance approval → project procurement",
    priority: 1, nextQuestion: "Which benefit stream could fund beds, and what are proposal and approval dates?",
    sourceUrl: "https://www.clc.org.au/strengthening-our-communities/", gsId: "AU-ABN-71979619393", match: 'legal-name' },
  { region: "Central Desert & Barkly", name: "NPY Women’s Council – Tjungu", orgType: "Health / disability / aged care support",
    role: "Customer / referrer", modelRoles: ["buyer", "referrer"],
    purchaseStatus: "Potential buyer/referrer", evidenceStatus: "Strong potential",
    payerRoute: "NDIS / My Aged Care / programme budgets", pathway: "Participant need → evidence/funding approval → supplier quote → order",
    priority: 1, nextQuestion: "Does Tjungu buy, refer or coordinate, and what functional evidence is required?",
    sourceUrl: "https://www.npywc.org.au/pages/tjungu-aged-and-disability-service", gsId: "AU-ABN-77902127562", match: 'legal-name' },
  { region: "Central Desert & Barkly", name: "Julalikari Council Aboriginal Corporation", orgType: "Aboriginal community organisation",
    role: "Repeat purchaser / possible production partner", modelRoles: ["buyer", "producer"],
    purchaseStatus: "Confirmed repeat buyer", evidenceStatus: "Confirmed purchase",
    payerRoute: "Organisation / grant / enterprise budgets", pathway: "Need or project → quote/invoice → delivery",
    priority: 1, nextQuestion: "Confirm bed quantity, funding source, repeat cycle and production-facility plans.",
    sourceUrl: null, gsId: "AU-ABN-52109391552", match: 'exact' },
  { region: "Central Desert & Barkly", name: "Our Community Shed, Tennant Creek", orgType: "Community organisation",
    role: "Buyer / possible production enterprise", modelRoles: ["buyer", "producer"],
    purchaseStatus: "Confirmed buyer", evidenceStatus: "Confirmed purchase",
    payerRoute: "Grant / organisation budget", pathway: "Grant → purchase → possible local production",
    priority: 1, nextQuestion: "Confirm production-facility status, future sales role and reorder potential.",
    sourceUrl: null, gsId: "AU-ABN-45406963505", match: 'legal-name' },
  { region: "North East Arnhem Land", name: "Bawinanga Aboriginal Corporation", orgType: "Aboriginal corporation / retail / logistics",
    role: "Community seller / logistics partner", modelRoles: ["seller"],
    purchaseStatus: "Potential channel", evidenceStatus: "Strong potential",
    payerRoute: "Retail / community / housing budgets", pathway: "Supplier onboarding → stock purchase → local distribution",
    priority: 1, nextQuestion: "Which unit can hold stock and invoice, and can Tucker Run distribute beds?",
    sourceUrl: "https://www.bawinanga.com/", gsId: "AU-ABN-58572395053", match: 'check' },
  { region: "North East Arnhem Land", name: "ALPA", orgType: "Indigenous corporation / remote retail",
    role: "Regional distributor / seller / buyer", modelRoles: ["seller", "channel", "buyer"],
    purchaseStatus: "Potential channel", evidenceStatus: "Strong potential",
    payerRoute: "Wholesale / stores / programme budgets", pathway: "Central range review → supplier onboarding → store trial → replenishment",
    priority: 1, nextQuestion: "Does ALPA centrally range household products, and what are onboarding and commercial terms?",
    sourceUrl: "https://www.alpa.asn.au/", gsId: "AU-ABN-52755439387", match: 'legal-name' },
  { region: "North East Arnhem Land", name: "Laynhapuy Homelands Aboriginal Corporation", orgType: "Homelands service organisation",
    role: "Community seller / institutional buyer", modelRoles: ["seller", "buyer"],
    purchaseStatus: "Potential buyer", evidenceStatus: "Potential",
    payerRoute: "Store / housing / support programme budgets", pathway: "Programme or store need → approval → quote/order → freight",
    priority: 2, nextQuestion: "Can a homeland store hold stock and do housing/support programs purchase beds?",
    sourceUrl: "https://www.laynhapuy.com.au/", gsId: "AU-ABN-86695642473", match: 'exact' },
  { region: "North East Arnhem Land", name: "Homeland School Company, Maningrida", orgType: "Education / homelands organisation",
    role: "Institutional buyer", modelRoles: ["buyer"],
    purchaseStatus: "Confirmed buyer", evidenceStatus: "Confirmed purchase",
    payerRoute: "Organisation / programme funding", pathway: "Need → local approval → quote/invoice → bulk delivery",
    priority: 1, nextQuestion: "Confirm funding source, family selection, feedback, repeat need and permission to cite.",
    sourceUrl: "https://www.goodsoncountry.com/beds", gsId: "AU-ABN-90668321088", match: 'legal-name' },
  { region: "North East Arnhem Land", name: "Mala'la Health Service Aboriginal Corporation", orgType: "Aboriginal health service",
    role: "Institutional buyer / referrer", modelRoles: ["buyer", "referrer"],
    purchaseStatus: "Confirmed buyer", evidenceStatus: "Confirmed purchase",
    payerRoute: "Health / social-support programme budget", pathway: "Service need → budget approval → quote/invoice",
    priority: 1, nextQuestion: "Confirm use case, programme, buyer authority and likely repeat volume.",
    sourceUrl: "https://www.goodsoncountry.com/beds", gsId: "AU-ABN-89357836457", match: 'exact' },
  { region: "North East Arnhem Land", name: "Miwatj Health", orgType: "Aboriginal community-controlled health service",
    role: "Customer / referrer", modelRoles: ["buyer", "referrer"],
    purchaseStatus: "Potential buyer", evidenceStatus: "Potential",
    payerRoute: "Health / aged care / disability / support budgets", pathway: "Client/program need → approval or referral → supplier quote",
    priority: 1, nextQuestion: "Does Miwatj buy household equipment or refer through NDIS/aged care?",
    sourceUrl: "https://www.miwatj.com.au/about-us/", gsId: "AU-ABN-96843428729", match: 'legal-name' },
  { region: "Kimberley", name: "Nirrumbuk Environmental Health and Services", orgType: "Regional Aboriginal organisation",
    role: "Community seller / housing customer", modelRoles: ["seller", "buyer"],
    purchaseStatus: "Potential buyer", evidenceStatus: "Strong potential",
    payerRoute: "Housing / environmental health / programme budgets", pathway: "Project need → quote/tender/onboarding → delivery",
    priority: 1, nextQuestion: "Does Nirrumbuk procure household goods or hold stock, and who owns the budget?",
    sourceUrl: "https://kimberleysupports.org.au/about-kimberley-supports/", gsId: "AU-ABN-70166603747", match: 'legal-name' },
  { region: "Kimberley", name: "Kununurra Waringarri Aboriginal Corporation", orgType: "Aboriginal organisation",
    role: "Community seller / connector", modelRoles: ["seller", "connector"],
    purchaseStatus: "Potential Channel", evidenceStatus: "Potential",
    payerRoute: "Enterprise / community / grant funding", pathway: "Enterprise decision → supplier agreement → stock and local distribution",
    priority: 2, nextQuestion: "Assess legal ability and appetite to resell, warehouse capacity, reach and margin.",
    sourceUrl: "https://kimberleysupports.org.au/about-kimberley-supports/", gsId: "AU-ABN-62195764089", match: 'exact' },
  { region: "Kimberley", name: "KAMS / Kimberley Supports", orgType: "Health and disability consortium",
    role: "Connector / buyer / referrer", modelRoles: ["buyer", "referrer", "connector"],
    purchaseStatus: "Potential buyer", evidenceStatus: "Strong potential",
    payerRoute: "NDIS / aged care / institutional programme budgets", pathway: "Client/program need → eligibility and funding → supplier quote/order",
    priority: 1, nextQuestion: "Could the product qualify in participant cases and can members aggregate institutional demand?",
    sourceUrl: "https://kams.org.au/programs/community-connector-cc-and-community-connector-coordinator-ccc-program/", gsId: "AU-ABN-67169851861", match: 'check' },
  { region: "Kimberley", name: "BRAMS, DAHS, OVAHS and YYMS", orgType: "Regional Aboriginal health organisations",
    role: "Institutional customers / referrers", modelRoles: ["buyer", "referrer"],
    purchaseStatus: "Potential buyer", evidenceStatus: "Potential",
    payerRoute: "Health / aged care / discretionary support budgets", pathway: "Need → internal approval/funding → supplier quote/order",
    priority: 2, nextQuestion: "Do services buy bedding or only refer, and which budgets and evidence apply?",
    sourceUrl: "https://kimberleysupports.org.au/about-kimberley-supports/", gsId: null, match: 'none' },
  { region: "Kimberley", name: "WA Housing and Works / Aboriginal housing providers", orgType: "Government / funded housing",
    role: "Institutional housing buyer", modelRoles: ["buyer"],
    purchaseStatus: "Potential buyer", evidenceStatus: "Potential",
    payerRoute: "Housing programme / government procurement", pathway: "Specification and eligibility → panel/tender/quote → order",
    priority: 1, nextQuestion: "Is bedding eligible, and what panels, specifications and Indigenous procurement routes apply?",
    sourceUrl: "https://www.wa.gov.au/government/publications/general-procurement-direction-202503-aboriginal-procurement-policy", gsId: null, match: 'none' },
  { region: "Kimberley", name: "KLC / KRED / PBC network", orgType: "Land council / economic development / PBC network",
    role: "Connector / royalty-funded customer", modelRoles: ["buyer", "funder", "connector"],
    purchaseStatus: "Potential Funder", evidenceStatus: "Strong potential",
    payerRoute: "PBC / trust / royalty / foundation funds", pathway: "Community/PBC proposal → board approval → quote or tender → coordinated delivery",
    priority: 1, nextQuestion: "Which PBCs or trusts fund household infrastructure, and what are decision rules and cycles?",
    sourceUrl: "https://www.klc.org.au/", gsId: "AU-ABN-96724252047", match: 'check' },
  { region: "Cape York & Palm Island", name: "Community Enterprise Queensland", orgType: "Remote retail organisation",
    role: "Distributor / retailer / community seller", modelRoles: ["seller", "channel"],
    purchaseStatus: "Potential channel", evidenceStatus: "Strong potential",
    payerRoute: "Wholesale / retail / community purchasing", pathway: "Supplier onboarding/range review → wholesale quote → consolidated order → stores",
    priority: 1, nextQuestion: "Will CEQ range, wholesale or freight the product; what margins, trial and warranty terms apply?",
    sourceUrl: "https://www.ceqld.org.au/our-stores/", gsId: "AU-ABN-42060262890", match: 'exact' },
  { region: "Cape York & Palm Island", name: "Cape York Partnership O-Hubs", orgType: "Community hubs",
    role: "Demand aggregator / community channel", modelRoles: ["channel"],
    purchaseStatus: "Potential channel", evidenceStatus: "Potential",
    payerRoute: "Community purchase / savings / programme funding", pathway: "Community demand aggregation → legal selling/invoicing route → distribution",
    priority: 2, nextQuestion: "Can O-Hubs hold or sell stock, and which entity invoices and retains margin?",
    sourceUrl: "https://capeyorkpartnership.org.au/our-partnership/o-hub/", gsId: "AU-ABN-67161760738", match: 'legal-name' },
  { region: "Cape York & Palm Island", name: "Local Aboriginal and Island councils", orgType: "Local government / community governance",
    role: "Community seller / housing buyer", modelRoles: ["seller", "buyer"],
    purchaseStatus: "Potential buyer", evidenceStatus: "Potential",
    payerRoute: "Council / housing / community-services budget", pathway: "Budget planning → procurement policy/quotes → order and local distribution",
    priority: 1, nextQuestion: "Identify the strongest named council, enterprise appetite, thresholds and budget timing.",
    sourceUrl: null, gsId: null, match: 'none' },
  { region: "Cape York & Palm Island", name: "Apunipima Cape York Health Council", orgType: "Regional Aboriginal health organisation",
    role: "Institutional buyer / referrer", modelRoles: ["buyer", "referrer"],
    purchaseStatus: "Potential buyer", evidenceStatus: "Potential",
    payerRoute: "Health / social-support / aged care / disability budgets", pathway: "Use case → eligibility/budget approval → supplier quote/order",
    priority: 1, nextQuestion: "Does Apunipima buy household equipment and what evidence and delegation apply?",
    sourceUrl: "https://apunipima.org.au/about/apunipima/our-communities/", gsId: "AU-ABN-26089437717", match: 'legal-name' },
  { region: "Cape York & Palm Island", name: "Queensland Health / Hospital and Health Services", orgType: "Government health",
    role: "Institutional buyer", modelRoles: ["buyer"],
    purchaseStatus: "Potential buyer", evidenceStatus: "Potential",
    payerRoute: "Government health / patient-support programme", pathway: "Valid use case → supplier eligibility → tender/panel/quote → purchase order",
    priority: 2, nextQuestion: "Is there an eligible clinical/discharge/support use case and what standards and thresholds apply?",
    sourceUrl: "https://www.health.qld.gov.au/system-governance/suppliers/information/doing-business-with-us/tender-opportunities", gsId: null, match: 'none' },
  { region: "Remote South Australia", name: "Yalata Anangu Aboriginal Corporation / General Store", orgType: "Aboriginal corporation / community store",
    role: "Community seller", modelRoles: ["seller"],
    purchaseStatus: "Potential channel", evidenceStatus: "Potential",
    payerRoute: "Retail / community / organisation budgets", pathway: "Board approval → stock purchase → store sale and local delivery",
    priority: 1, nextQuestion: "Will the organisation hold and sell stock, and what margin, storage, credit and freight apply?",
    sourceUrl: "https://yalata.com.au/about-us/yalata-services/", gsId: "AU-ABN-23404857519", match: 'legal-name' },
  { region: "Remote South Australia", name: "Oak Valley (Maralinga) Inc.", orgType: "Community organisation",
    role: "Community seller / housing customer", modelRoles: ["seller", "buyer"],
    purchaseStatus: "Potential buyer", evidenceStatus: "Potential",
    payerRoute: "Housing / store / health / aged-care budgets", pathway: "Community approval → budget → quote/order → freight and stock",
    priority: 1, nextQuestion: "Which entity can sell beds and who owns bedding procurement and storage?",
    sourceUrl: "https://oakvalley.com.au/programs/", gsId: "AU-ABN-19598209330", match: 'legal-name' },
  { region: "Remote South Australia", name: "Tullawon Health Service", orgType: "Aboriginal-controlled health service",
    role: "Institutional buyer / referrer", modelRoles: ["buyer", "referrer"],
    purchaseStatus: "Potential buyer", evidenceStatus: "Potential",
    payerRoute: "Health / aged care / disability funding", pathway: "Client/program need → evidence/funding → quote/order or referral",
    priority: 1, nextQuestion: "Does Tullawon buy bedding or refer clients, and who approves?",
    sourceUrl: "https://www.tullawon.org.au/", gsId: "AU-ABN-97478220756", match: 'legal-name' },
  { region: "Remote South Australia", name: "SA Housing Trust / regional housing services", orgType: "Government / housing",
    role: "Institutional housing buyer", modelRoles: ["buyer"],
    purchaseStatus: "Potential buyer", evidenceStatus: "Potential",
    payerRoute: "Housing / support programme / government procurement", pathway: "Eligibility/specification → panel/tender/quote → order",
    priority: 1, nextQuestion: "Is bedding eligible and what programme, panel, standards and purchasing cycle apply?",
    sourceUrl: null, gsId: null, match: 'none' },
  { region: "Remote South Australia", name: "Far West Community Partnerships", orgType: "Aboriginal-led place-based organisation",
    role: "Connector / demand aggregator", modelRoles: ["channel", "connector"],
    purchaseStatus: "Potential Channel", evidenceStatus: "Potential",
    payerRoute: "Place-based / government / philanthropic project funding", pathway: "Convene local buyers → define project → funding/procurement route",
    priority: 2, nextQuestion: "Can the organisation convene buyers and sponsor projects, and when is the next planning cycle?",
    sourceUrl: "https://www.fwcp.com.au/our-team", gsId: "AU-ABN-88651438238", match: 'legal-name' },
  { region: "Cross-region", name: "Snow Foundation", orgType: "Foundation / funder",
    role: "Buyer and funder", modelRoles: ["buyer", "funder"],
    purchaseStatus: "Confirmed buyer", evidenceStatus: "Confirmed purchase",
    payerRoute: "Philanthropic grant deployment", pathway: "Grant decision → direct purchase/invoice → delivery",
    priority: 1, nextQuestion: "Confirm regions/beneficiaries, permission to cite and whether future cycles exist.",
    sourceUrl: null, gsId: "AU-ABN-49411415493", match: 'check' },
  { region: "Cross-region", name: "Red Dust", orgType: "Youth / community programme organisation",
    role: "Buyer / youth-employment partner", modelRoles: ["buyer"],
    purchaseStatus: "Confirmed buyer", evidenceStatus: "Confirmed purchase",
    payerRoute: "Programme / partnership funding", pathway: "Programme need → quote/purchase; partnership route to develop",
    priority: 1, nextQuestion: "Confirm geography, funding and concrete next step for youth employment partnership.",
    sourceUrl: null, gsId: "AU-ABN-12118641777", match: 'check' },
  { region: "Cross-region", name: "QIC", orgType: "Corporate",
    role: "Corporate RAP buyer", modelRoles: ["buyer"],
    purchaseStatus: "Confirmed buyer", evidenceStatus: "Confirmed purchase",
    payerRoute: "Corporate RAP budget", pathway: "RAP initiative → internal approval → purchase",
    priority: 2, nextQuestion: "Identify current RAP owner, repeat opportunity and suitable regional partner.",
    sourceUrl: null, gsId: "AU-ABN-83076279528", match: 'check' },
  { region: "Cross-region", name: "Rotary eClub Outback Australia", orgType: "Service club / philanthropic",
    role: "Buyer / project funder", modelRoles: ["buyer", "funder"],
    purchaseStatus: "Confirmed buyer", evidenceStatus: "Confirmed / caution",
    payerRoute: "Philanthropic / project funding", pathway: "Project commitment → invoice/payment → production/delivery; payment controls required",
    priority: 3, nextQuestion: "Confirm current payment status and apply deposit/payment-before-delivery controls.",
    sourceUrl: null, gsId: "AU-ABN-92451304504", match: 'legal-name' },
];
