import { getServiceSupabase } from '@/lib/supabase';

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Types
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export interface FounderIntake {
  id: string;
  user_id: string | null;
  org_profile_id: string | null;
  idea_summary: string | null;
  problem_statement: string | null;
  target_beneficiary: Record<string, unknown> | null;
  issue_areas: string[] | null;
  geographic_focus: Record<string, unknown> | null;
  founder_motivation: string | null;
  existing_orgs_shown: unknown[] | null;
  differentiation: string | null;
  partnership_decision: string | null;
  recommended_entity_type: string | null;
  entity_type_rationale: string | null;
  entity_type_scores: unknown[] | null;
  revenue_model: string[] | null;
  matched_alma_interventions: unknown[] | null;
  evidence_gaps: string[] | null;
  matched_grants: unknown[] | null;
  matched_foundations: unknown[] | null;
  procurement_pathways: unknown[] | null;
  action_plan: unknown[] | null;
  project_brief_md: string | null;
  draft_email: string | null;
  phase: string;
  status: string;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface IntakeMessage {
  id: string;
  intake_id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  phase: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// CRUD
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export async function createIntake(): Promise<FounderIntake | null> {
  const supabase = getServiceSupabase();
  const { data, error } = await supabase
    .from('founder_intakes')
    .insert({})
    .select()
    .single();
  if (error) return null;
  return data as FounderIntake;
}

export async function getIntake(id: string): Promise<FounderIntake | null> {
  const supabase = getServiceSupabase();
  const { data, error } = await supabase
    .from('founder_intakes')
    .select('*')
    .eq('id', id)
    .maybeSingle();
  if (error || !data) return null;
  return data as FounderIntake;
}

export async function updateIntake(
  id: string,
  updates: Partial<FounderIntake>,
): Promise<FounderIntake | null> {
  const supabase = getServiceSupabase();
  const { data, error } = await supabase
    .from('founder_intakes')
    .update({ ...updates, updated_at: new Date().toISOString() })
    .eq('id', id)
    .select()
    .single();
  if (error) return null;
  return data as FounderIntake;
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Messages
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export async function getIntakeMessages(intakeId: string): Promise<IntakeMessage[]> {
  const supabase = getServiceSupabase();
  const { data } = await supabase
    .from('founder_intake_messages')
    .select('*')
    .eq('intake_id', intakeId)
    .order('created_at');
  return (data ?? []) as IntakeMessage[];
}

export async function addIntakeMessage(
  intakeId: string,
  role: 'user' | 'assistant' | 'system',
  content: string,
  phase?: string,
): Promise<IntakeMessage | null> {
  const supabase = getServiceSupabase();
  const { data, error } = await supabase
    .from('founder_intake_messages')
    .insert({ intake_id: intakeId, role, content, phase })
    .select()
    .single();
  if (error) return null;
  return data as IntakeMessage;
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Brief Generation
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export function generateBrief(intake: FounderIntake): string {
  const sections: string[] = [];

  sections.push(`# ${intake.idea_summary || 'Project Brief'}\n`);
  sections.push(`*Generated by CivicGraph — ${new Date().toLocaleDateString('en-AU')}*\n`);

  if (intake.problem_statement) {
    sections.push(`## The Problem\n\n${intake.problem_statement}\n`);
  }

  if (intake.founder_motivation) {
    sections.push(`## Why This Matters\n\n${intake.founder_motivation}\n`);
  }

  const beneficiary = intake.target_beneficiary;
  const geo = intake.geographic_focus;
  if (beneficiary || geo) {
    let text = '## Who We Serve\n\n';
    if (beneficiary) {
      if (typeof beneficiary === 'object') {
        const parts: string[] = [];
        if ('cohort' in beneficiary) parts.push(`**Cohort:** ${beneficiary.cohort}`);
        if ('location' in beneficiary) parts.push(`**Location:** ${beneficiary.location}`);
        if ('demographics' in beneficiary) parts.push(`**Demographics:** ${beneficiary.demographics}`);
        text += parts.join('\n') + '\n';
      }
    }
    if (geo) {
      const parts: string[] = [];
      if ('state' in geo) parts.push(`**State:** ${geo.state}`);
      if ('lga' in geo) parts.push(`**LGA:** ${geo.lga}`);
      if ('postcode' in geo) parts.push(`**Postcode:** ${geo.postcode}`);
      text += parts.join('\n') + '\n';
    }
    sections.push(text);
  }

  if (intake.issue_areas && intake.issue_areas.length > 0) {
    sections.push(`## Issue Areas\n\n${intake.issue_areas.map(a => `- ${a}`).join('\n')}\n`);
  }

  if (intake.recommended_entity_type) {
    sections.push(`## Recommended Structure\n\n**${intake.recommended_entity_type}**\n\n${intake.entity_type_rationale || ''}\n`);
  }

  if (intake.matched_alma_interventions && Array.isArray(intake.matched_alma_interventions) && intake.matched_alma_interventions.length > 0) {
    let text = '## Evidence Base\n\nMatched ALMA interventions:\n\n';
    for (const m of intake.matched_alma_interventions as Array<{ name: string; type: string; evidence_level: string }>) {
      text += `- **${m.name}** (${m.type}) — Evidence: ${m.evidence_level}\n`;
    }
    sections.push(text);
  }

  if (intake.matched_grants && Array.isArray(intake.matched_grants) && intake.matched_grants.length > 0) {
    let text = '## Funding Opportunities\n\n';
    for (const g of intake.matched_grants as Array<{ name: string; amount_max: number; deadline: string; provider: string }>) {
      const amount = g.amount_max ? `$${(g.amount_max / 1000).toFixed(0)}K` : 'Amount varies';
      text += `- **${g.name}** — ${g.provider || 'Various'}. ${amount}.${g.deadline ? ` Deadline: ${g.deadline}` : ''}\n`;
    }
    sections.push(text);
  }

  if (intake.matched_foundations && Array.isArray(intake.matched_foundations) && intake.matched_foundations.length > 0) {
    let text = '## Foundation Matches\n\n';
    for (const f of intake.matched_foundations as Array<{ name: string; total_giving_annual: number }>) {
      const giving = f.total_giving_annual ? `$${(f.total_giving_annual / 1000).toFixed(0)}K/year` : '';
      text += `- **${f.name}**${giving ? ` — ${giving}` : ''}\n`;
    }
    sections.push(text);
  }

  if (intake.action_plan && Array.isArray(intake.action_plan) && intake.action_plan.length > 0) {
    let text = '## 90-Day Action Plan\n\n';
    for (const step of intake.action_plan as Array<{ step: string; description: string; timeline: string }>) {
      text += `### ${step.step}\n${step.description}\n*Timeline: ${step.timeline}*\n\n`;
    }
    sections.push(text);
  }

  if (intake.draft_email) {
    sections.push(`## Draft Outreach Email\n\n\`\`\`\n${intake.draft_email}\n\`\`\`\n`);
  }

  if (intake.differentiation) {
    sections.push(`## What Makes This Different\n\n${intake.differentiation}\n`);
  }

  sections.push(`---\n\n*Powered by CivicGraph — Decision Infrastructure for Government & Social Sector*\n*Data from: ALMA (Australian Living Map of Alternatives), AusTender, ACNC, ATO, GrantConnect*`);

  return sections.join('\n');
}
