-- Bring the projects table in line with act-global config/project-codes.json (Ben, 2026-09-26: the file is the
-- one source of truth). Generated by scripts/sync-projects-table-sql.mjs from the file as of act-global PR #277
-- (MMEIC folded into Quandamooka). Statuses follow Ben's project code review (thoughts/shared/drafts/
-- 2026-09-26-project-code-review*). Descriptions and tiers are kept. Nothing is deleted: ACT-PC and ACT-MM are
-- archived with merged_into ACT-PI and ACT-QD.
--
-- Apply: scripts/db-apply.sh supabase/migrations/20260926140000_sync_projects_table_from_codes.sql (Tier 3, Ben's verb; after act-global #277 merges)

BEGIN;
INSERT INTO projects (code, name, status, tier, category, description, parent_project, organization_id, act_project_code, metadata)
  VALUES ('ACT-GS', 'CivicGraph', 'active', 'background', 'background', 'GrantScope tool / CivicGraph reference. Wiki page at wiki/projects/grantscope.md. Lives in separate repo at /Users/benknight/Code/grantscope.', NULL, '88f84b66-f0fd-4fcf-9ec9-3cfc682303c5', 'ACT-GS', jsonb_build_object('legacy_codes', '["ACT-JH-CG"]'::jsonb, 'synced_from', 'project-codes.json'));
INSERT INTO projects (code, name, status, tier, category, description, parent_project, organization_id, act_project_code, metadata)
  VALUES ('ACT-TV', 'The Vagina', 'ideation', 'studio', 'arts', 'An ACT Studio piece in early development. The working title is public, but its question, materials, collaborators and exhibition context are not yet documented. This page holds its place without prete', NULL, '88f84b66-f0fd-4fcf-9ec9-3cfc682303c5', 'ACT-TV', jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'));
INSERT INTO projects (code, name, status, tier, category, description, parent_project, organization_id, act_project_code, metadata)
  VALUES ('ACT-CVN', 'The Caravan', 'dormant', 'studio', 'arts', 'Born at the 10x10 Community Capital Leadership Retreat, The Caravan is a hand-built room on wheels that travels between communities for leadership gatherings, listening sessions and on-Country convers', 'ACT-CP', '88f84b66-f0fd-4fcf-9ec9-3cfc682303c5', 'ACT-CVN', jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'));
INSERT INTO projects (code, name, status, tier, category, description, parent_project, organization_id, act_project_code, metadata)
  VALUES ('ACT-PK', 'PICC Photo Kiosk', 'dormant', 'studio', 'indigenous', 'On Palm Island (Bwgcolman), a self-service photo station at the Palm Island Community Company shifted who holds the camera. Families, elders, young people and visitors documented their own stories on ', 'ACT-PI', '88f84b66-f0fd-4fcf-9ec9-3cfc682303c5', 'ACT-PK', jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'));
INSERT INTO projects (code, name, status, tier, category, description, parent_project, organization_id, act_project_code, metadata)
  VALUES ('ACT-CTP', 'Confessions to Philanthropy', 'active', 'studio', 'arts', 'Confessions to Philanthropy is a gold phone and an anonymous voicemail for the sector that funds change. Callers leave unscripted messages about giving and power, the awkward and hopeful and unsaid, a', 'ACT-CS', '88f84b66-f0fd-4fcf-9ec9-3cfc682303c5', 'ACT-CTP', jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'));
INSERT INTO projects (code, name, status, tier, category, description, parent_project, organization_id, act_project_code, metadata)
  VALUES ('ACT-SP', 'Station Precinct', 'active', 'background', 'indigenous', 'Station Precinct in Townsville: adaptive reuse of a heritage police station as a community and enterprise hub, with PICC. Its own code from 2026-09-26 (was ACT-PI-SP in CivicGraph).', 'ACT-PI', '88f84b66-f0fd-4fcf-9ec9-3cfc682303c5', 'ACT-SP', jsonb_build_object('legacy_codes', '["ACT-PI-SP"]'::jsonb, 'synced_from', 'project-codes.json'));
INSERT INTO projects (code, name, status, tier, category, description, parent_project, organization_id, act_project_code, metadata)
  VALUES ('ACT-AL', 'Australian Living Map of Alternatives (ALMA)', 'active', 'background', 'justice', 'Australian Living Map of Alternatives (ALMA), its own code from 2026-09-26 (was ACT-JH-AL in CivicGraph) (Ben, project code review 2026-09-26).', 'ACT-JH', '88f84b66-f0fd-4fcf-9ec9-3cfc682303c5', 'ACT-AL', jsonb_build_object('legacy_codes', '["ACT-JH-AL"]'::jsonb, 'synced_from', 'project-codes.json'));
UPDATE projects SET name = 'Diagrama', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-DG';
UPDATE projects SET name = 'PICC Elders Room', status = 'active', parent_project = 'ACT-PI',
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '["ACT-PI-ER"]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-ER';
UPDATE projects SET name = 'PICC On Country Photo Studio', status = 'dormant', parent_project = 'ACT-PI',
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-PS';
UPDATE projects SET name = 'MingaMinga Rangers', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-MR';
UPDATE projects SET name = 'Uncle Allan Palm Island Art', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-UA';
UPDATE projects SET name = 'The Farm', status = 'active', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '["ACT-BV","ACT-BCV"]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-FM';
UPDATE projects SET name = 'Contained', status = 'active', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '["ACT-JH-CT"]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-CN';
UPDATE projects SET name = 'Fishers Oysters', status = 'active', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-FO';
UPDATE projects SET name = 'CAMPFIRE', status = 'active', parent_project = 'ACT-BG',
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-CM';
UPDATE projects SET name = 'ACT Monthly Dinners', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-MD';
UPDATE projects SET name = 'BG Fit', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-BG';
UPDATE projects SET name = 'Civic Scope', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '["ACT-CG"]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-CS';
UPDATE projects SET name = 'Community Capital', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-CP';
UPDATE projects SET name = 'ConFit Pathways', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-CT';
UPDATE projects SET name = 'The Shed', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-SH';
UPDATE projects SET name = 'SEFA Partnership', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-SE';
UPDATE projects SET name = 'Custodian First Economy', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-CE';
UPDATE projects SET name = 'Deadly Homes and Gardens', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-DH';
UPDATE projects SET name = 'Cars and Microcontrollers', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-MC';
UPDATE projects SET name = 'Barkly Backbone', status = 'archived', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-BB';
UPDATE projects SET name = 'JusticeHub Centre of Excellence', status = 'active', parent_project = 'ACT-JH',
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-JC';
UPDATE projects SET name = 'Designing for Obsolescence', status = 'active', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-DO';
UPDATE projects SET name = 'Global Laundry Alliance', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-GL';
UPDATE projects SET name = 'Fairfax PLACE Tech', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-FP';
UPDATE projects SET name = 'Orange Sky EL', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-OS';
UPDATE projects SET name = 'Feel Good Project', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-FG';
UPDATE projects SET name = 'Place-Based Policy Lab', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-PB';
UPDATE projects SET name = 'Deadly Labs', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-DLB';
UPDATE projects SET name = 'Quandamooka Justice and Healing Strategy', status = 'active', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '["ACT-MM"]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-QD';
UPDATE projects SET name = 'ReSOLEution', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-RS';
UPDATE projects SET name = 'Black Cockatoo Valley', status = 'active', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-BV';
UPDATE projects SET name = 'CivicGraph (CivicScope)', status = 'dormant', parent_project = NULL,
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('legacy_codes', '[]'::jsonb, 'synced_from', 'project-codes.json'), updated_at = now()
  WHERE code = 'ACT-CG';
UPDATE projects SET status = 'archived', updated_at = now(),
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('retired', 'not in project-codes.json', 'merged_into', 'ACT-PI')
  WHERE code = 'ACT-PC';
UPDATE projects SET status = 'archived', updated_at = now(),
  metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('retired', 'not in project-codes.json', 'merged_into', 'ACT-QD')
  WHERE code = 'ACT-MM';

COMMIT;
