export type QldAnnouncementSource = {
  label: string;
  kind: 'budget' | 'statement' | 'tracker' | 'dossier' | 'charter' | 'program' | 'report' | 'opendata';
  url: string;
  note: string;
};

export type QldAnnouncementProviderLead = {
  name: string;
  role: string;
  source: string;
  status: 'named publicly' | 'sql signal' | 'tracker signal' | 'needs confirmation';
  entityStatus?: 'linked' | 'likely-match' | 'needs-abn' | 'needs-contact' | 'needs-confirmation' | 'system-actor';
  abn?: string;
  gsId?: string;
  knownFacts?: string[];
  askNext?: string[];
  lockedInfo?: string[];
  outreachAngle?: string;
  contactEmail?: string;
  contactPhone?: string;
  website?: string;
};

export type QldAnnouncementPublicLink = {
  label: string;
  href: string;
  note: string;
  kind: 'report' | 'entity' | 'tracker' | 'funding' | 'admin';
};

export type QldAnnouncementPublicBrief = {
  headline: string;
  intro: string;
  readerNotes: string[];
  usefulInformation: string[];
  civicLinks: QldAnnouncementPublicLink[];
  adminActions: string[];
};

export type QldAnnouncement = {
  slug: string;
  title: string;
  amountLabel: string;
  amountValue: number;
  sourceLabel: string;
  status: 'named-sql' | 'provider-sql' | 'official-only' | 'not-visible';
  summary: string;
  whyItMatters: string;
  serviceAreas: string[];
  providerLeads: QldAnnouncementProviderLead[];
  sourceLinks: QldAnnouncementSource[];
  matchingWorkflow: string[];
  justiceHubOutreach: string[];
  missingProof: string[];
  articleAngle: string;
  centreOfExcellenceUse: string;
  publicBrief?: QldAnnouncementPublicBrief;
};

export const qldYouthJusticeAnnouncements: QldAnnouncement[] = [
  {
    slug: 'staying-on-track',
    title: 'Staying on Track',
    amountLabel: '$225m over 5 years',
    amountValue: 225_000_000,
    sourceLabel: '2025-26 Budget Paper 4',
    status: 'provider-sql',
    summary: 'Twelve months of post-release rehabilitation support for young people exiting detention.',
    whyItMatters: 'This is the clearest place to test whether Queensland is funding throughcare after detention or just announcing a pathway without a visible provider ledger.',
    serviceAreas: ['post-release support', 'reintegration', 'family support', 'mentoring', 'place-based case work', 'throughcare'],
    providerLeads: [
      {
        name: 'Life Without Barriers',
        role: 'Gold Coast rollout lead publicly named',
        source: 'Ministerial statement',
        status: 'named publicly',
        entityStatus: 'linked',
        abn: '15101252171',
        gsId: 'AU-ABN-15101252171',
        knownFacts: ['QLD youth-justice snapshot links 7 rows worth about $12.7m', 'Programs include Social Services, Flexible Respite, EPCS, and Young People rows'],
        askNext: ['Confirm the Staying on Track delivery region and referral pathway', 'Identify the right practice lead for anonymised story and method evidence'],
        lockedInfo: ['young person identities', 'case files', 'unpublished referral lists', 'family contact details'],
        outreachAngle: 'Ask how throughcare is working after detention and what evidence can be shared safely without exposing young people or families.',
        contactEmail: 'info@lwb.org.au',
        contactPhone: '1300 592 227',
        website: 'https://www.lwb.org.au',
      },
      {
        name: 'Fearless Towards Success',
        role: 'South East rollout provider publicly named',
        source: 'Ministerial statement',
        status: 'named publicly',
        entityStatus: 'linked',
        abn: '67649238648',
        gsId: 'AU-ABN-67649238648',
        knownFacts: ['QLD youth-justice snapshot links 1 Social Services row worth about $6.5m', 'Named publicly for South East Staying on Track rollout'],
        askNext: ['Confirm whether the Social Services row is the same delivery pathway', 'Ask what support model and cohort are being delivered'],
        lockedInfo: ['participant names', 'justice orders', 'unpublished outcome data'],
        outreachAngle: 'Invite a conversation about what post-release support looks like in practice and what JusticeHub can document responsibly.',
        contactEmail: 'info@ftsqld.com.au',
        contactPhone: '0402 154 020',
        website: 'https://ftsqld.com.au',
      },
      {
        name: 'Anglicare Southern Queensland',
        role: 'South East rollout provider publicly named',
        source: 'Ministerial statement',
        status: 'named publicly',
        entityStatus: 'linked',
        abn: '84868235450',
        gsId: 'AU-ABN-84868235450',
        knownFacts: ['QLD snapshot links Anglicare Southern Queensland to AU-ABN-84868235450', 'The matched QLD youth-justice row is worth about $949k under Community, Youth Justice Services and Women'],
        askNext: ['Confirm whether this row is the Staying on Track delivery pathway', 'Confirm South East service footprint and contact owner'],
        lockedInfo: ['client details', 'internal subcontracting arrangements', 'unpublished delivery volumes'],
        outreachAngle: 'Use the linked entity record, then ask for a plain-language account of what the rollout changes for young people and families.',
        contactEmail: 'info@anglicaresq.org.au',
        contactPhone: '1300 610 610',
        website: 'https://anglicaresq.org.au',
      },
      {
        name: 'Village Support',
        role: 'South East rollout provider publicly named',
        source: 'Ministerial statement',
        status: 'named publicly',
        entityStatus: 'linked',
        abn: '30682255643',
        gsId: 'AU-ABN-30682255643',
        knownFacts: ['QLD youth-justice snapshot links 1 Social Services row worth about $2.6m', 'Named publicly for South East Staying on Track rollout'],
        askNext: ['Confirm program-name mapping to Staying on Track', 'Ask which communities and referral partners are involved'],
        lockedInfo: ['young person contact details', 'case plan information', 'non-public government correspondence'],
        outreachAngle: 'Ask what gap Village Support is filling in the throughcare pathway and what evidence would help the public understand it.',
        contactEmail: 'admin@villagesupport.org.au',
        contactPhone: '0435 526 123',
        website: 'https://villagesupport.org.au',
      },
      {
        name: 'Jabalbina Yalanji Aboriginal Corporation',
        role: 'Far North rollout provider publicly named',
        source: 'Ministerial statement',
        status: 'named publicly',
        entityStatus: 'linked',
        abn: '79611886178',
        gsId: 'AU-ABN-79611886178',
        knownFacts: ['QLD snapshot links Jabalbina to Kickstarter and Social Services rows', 'QLD lobbying register mirror also contains a Jabalbina entry'],
        askNext: ['Confirm the exact Staying on Track contracting record', 'Ask what community authority and consent process should govern any story'],
        lockedInfo: ['cultural knowledge not cleared for publication', 'young person or family details', 'community-sensitive location details'],
        outreachAngle: 'Approach through a consent-first lens: ask what Jabalbina wants documented and what should stay community-held.',
        contactEmail: 'reception@jabalbina.com.au',
        contactPhone: '07 4098 3552',
        website: 'https://www.jabalbina.com.au',
      },
      {
        name: 'Namu Collective',
        role: 'Far North and Townsville provider publicly named',
        source: 'Ministerial statement',
        status: 'named publicly',
        entityStatus: 'linked',
        abn: '32685061929',
        gsId: 'AU-ABN-32685061929',
        knownFacts: ['QLD youth-justice snapshot links 1 Social Services row worth about $2.1m', 'Named publicly for Far North and Townsville rollout'],
        askNext: ['Confirm service geography and delivery partners', 'Ask what evidence can be shared about culturally safe throughcare'],
        lockedInfo: ['client identities', 'unpublished location-level caseloads', 'private partner data'],
        outreachAngle: 'Ask how the Far North and Townsville model works and whether a de-identified practice note can be co-produced.',
        contactEmail: 'genus@namucollective.com',
        contactPhone: '1300 612 925',
        website: 'https://www.namucollective.com',
      },
      {
        name: 'Shine for Kids',
        role: 'Far North rollout provider publicly named',
        source: 'Ministerial statement',
        status: 'named publicly',
        entityStatus: 'linked',
        abn: '60662072775',
        gsId: 'AU-ABN-60662072775',
        knownFacts: ['QLD youth-justice snapshot links 2 Social Services rows worth about $13.3m', 'Named publicly for Far North Staying on Track rollout'],
        askNext: ['Confirm whether current Social Services rows include Staying on Track', 'Ask what family support and throughcare evidence can be shared'],
        lockedInfo: ['children and family identities', 'case histories', 'unpublished evaluation detail'],
        outreachAngle: 'Invite Shine for Kids to explain the family support side of post-release work and what outcomes should be visible publicly.',
        contactPhone: '02 9714 3000',
        website: 'https://shineforkids.org.au',
      },
    ],
    sourceLinks: [
      { kind: 'budget', label: 'Budget measure', url: 'https://budget.qld.gov.au/files/Budget-2025-26-BP4-Budget-Measures.pdf', note: 'Budget allocation for post-release rehabilitation support.' },
      { kind: 'statement', label: 'Budget media statement', url: 'https://statements.qld.gov.au/statements/102882', note: 'Early intervention and rehabilitation package context.' },
      { kind: 'statement', label: 'Life Without Barriers named', url: 'https://statements.qld.gov.au/statements/103190', note: 'First Staying on Track provider named publicly.' },
      { kind: 'statement', label: 'South East rollout', url: 'https://statements.qld.gov.au/statements/103605', note: 'Fearless, Anglicare, and Village Support named.' },
      { kind: 'statement', label: 'Far North rollout', url: 'https://statements.qld.gov.au/statements/103621', note: 'Jabalbina, Namu, and Shine for Kids named.' },
      { kind: 'statement', label: 'Townsville rollout', url: 'https://statements.qld.gov.au/statements/103667', note: 'Namu Collective named for Townsville.' },
    ],
    matchingWorkflow: [
      'Search funding rows for provider names and broad Community and Youth Justice Services labels.',
      'Resolve each provider to gs_entities, ACNC, ABN, and QLD service geography.',
      'Check QTenders and DYJVS contract disclosures for program-name rows that mention Staying on Track.',
      'Add provider contacts to the JusticeHub outreach board once identity and delivery area are confirmed.',
    ],
    justiceHubOutreach: [
      'Ask what post-release support actually looks like for young people and families.',
      'Ask how referral, consent, cultural authority, and community handover are handled.',
      'Ask whether providers can contribute anonymised practice evidence or lived-experience storytelling.',
    ],
    missingProof: ['Contract or grant rows naming Staying on Track', 'locations and referral pathways', 'delivery volumes', 'completion and re-contact outcomes'],
    articleAngle: 'Throughcare is the first test of whether Queensland is building a pathway out of detention or extending the detention system into community services.',
    centreOfExcellenceUse: 'Use this as one pillar in the JusticeHub Centre of Excellence case: we need a standing evidence layer that can see whether aftercare becomes real support.',
  },
  {
    slug: 'circuit-breaker-sentencing',
    title: 'Circuit Breaker Sentencing',
    amountLabel: '$80m over 4 years',
    amountValue: 80_000_000,
    sourceLabel: '2025-26 Budget Paper 4',
    status: 'named-sql',
    summary: 'Court-sentenced 3 to 6 month intensive rehabilitation across two remote regional facilities in North and South East Queensland, with combined capacity for up to 60 young people and delivery expected in 2026.',
    whyItMatters: 'This is the headline alternative to detention. The official program is now visible and the live funding table has a named DYJVS row, but the operators, locations, court pathway, and outcomes are still not public enough to prove whether children are being diverted from detention.',
    serviceAreas: ['court-sentenced alternative', '3 to 6 month rehabilitation', 'two remote regional facilities', 'North Queensland', 'South East Queensland', 'wraparound health and social services', 'education and skills training', 'market engagement'],
    providerLeads: [
      {
        name: 'Department of Youth Justice and Victim Support commissioning team',
        role: 'Public commissioning owner. Registrations of interest closed on 9 October 2025 and delivery is expected to commence in 2026.',
        source: 'Official program page + live SQL funding row',
        status: 'sql signal',
        entityStatus: 'system-actor',
        knownFacts: [
          'Official program page names YJCommissioning@youthjustice.qld.gov.au as the public contact.',
          'Live justice_funding has a 2025-26 Circuit Breaker Sentencing row for DYJVS worth $20m.',
          'Budget Paper 4 stages the $80m over 4 years as $20m, $30m, $20m, then $10m.',
          'Question on Notice 1145 said the tender process was set to occur as soon as possible.',
        ],
        askNext: [
          'Ask whether the ROI, RFO, shortlist, awarded operators, or contract notices can be released.',
          'Ask which parts of the program are public, commercially sensitive, or safety-sensitive.',
          'Ask when provider, location, referral, and outcome reporting will become visible.',
        ],
        lockedInfo: ['tender-confidential respondent material', 'security-sensitive facility details', 'young person identities and court files'],
        outreachAngle: 'Use the public commissioning email to request the transparent delivery trail: procurement stage, operator naming timeline, court eligibility, evidence model, and public reporting cadence.',
        contactEmail: 'YJCommissioning@youthjustice.qld.gov.au',
      },
      {
        name: 'Non-government facility operators',
        role: 'Two remote regional facilities are planned in northern Queensland and South East Queensland, but the operators are not yet named in the current public record.',
        source: 'Official program page + ministerial statement',
        status: 'needs confirmation',
        entityStatus: 'system-actor',
        knownFacts: [
          'The program is described as market-led and delivered with non-government organisations.',
          'Combined capacity is up to 60 youth offenders for 3 to 6 months.',
          'The announced model includes structure, discipline, education, rehabilitation, and wraparound health and social support.',
        ],
        askNext: [
          'Resolve operator names, ABNs, facility places, cultural governance, subcontractors, and service model.',
          'Check whether the facilities are new, repurposed, leased, or operated through an existing residential-care provider.',
          'Confirm whether local ACCOs or community-controlled organisations hold governance or delivery roles.',
        ],
        lockedInfo: ['unpublished site addresses if safety-sensitive', 'tender respondent lists before public award', 'participant movement or custody details'],
        outreachAngle: 'Do not treat this as a provider story until the operators are named. First build a delivery ledger: location, operator, ABN, contract, safeguards, and community authority.',
      },
      {
        name: 'Queensland courts and sentencing pathway',
        role: 'Courts are said to have the option to order young people into the program as an alternative to detention, but the exact legal mechanism and eligibility rules still need to be sourced.',
        source: 'Official program page, ministerial statement, and Hansard',
        status: 'needs confirmation',
        entityStatus: 'system-actor',
        knownFacts: [
          'Government material describes the model as court-sentenced, not voluntary referral only.',
          'Hansard says submissions closed on 9 October 2025 and frames the program as an alternative to detention.',
        ],
        askNext: [
          'Check Youth Justice Act amendments, regulation, court practice directions, and explanatory notes.',
          'Ask Legal Aid Queensland, ATSILS, Youth Advocacy Centre, and community legal services what court pathway is actually available.',
          'Track how many orders are made, refused, completed, breached, or converted to detention.',
        ],
        lockedInfo: ['individual court matters', 'young person identities', 'sealed or suppressed proceedings'],
        outreachAngle: 'JusticeHub should explain the legal pathway in plain English before telling any provider story, because the public test is whether courts can actually use the alternative.',
      },
      {
        name: 'Independent evidence and rights checks',
        role: 'QFCC reporting recognises the $80m commitment but warns that evaluation frameworks, performance indicators, implementation timelines, co-design, and equity analysis remain unclear.',
        source: 'QFCC Child Rights Report 2025 + QFCC performance report',
        status: 'needs confirmation',
        entityStatus: 'system-actor',
        knownFacts: [
          'The QFCC Child Rights Report says little detail is available on evaluation frameworks, performance indicators, or implementation timelines for new youth justice programs.',
          'The QFCC performance report describes Circuit Breaker as a three to six month alternative-to-detention rehabilitation program.',
        ],
        askNext: [
          'Create a simple evidence checklist: diversion from detention, cultural authority, family contact, health support, education, completion, reoffending, and child-rights safeguards.',
          'Ask whether an evaluation plan, human rights assessment, or service model will be published.',
          'Compare the model against ALMA alternatives and lived-experience evidence before accepting success claims.',
        ],
        lockedInfo: ['confidential evaluation data before consent or publication', 'individual participant records'],
        outreachAngle: 'Use QFCC as the independent accountability lens: the question is not just whether the facilities open, but whether the model is rights-safe, evidence-based, and transparent.',
      },
    ],
    sourceLinks: [
      { kind: 'program', label: 'Official program page', url: 'https://www.youthjustice.qld.gov.au/programs-initiatives/initiatives/circuit-breaker-sentencing', note: 'Registrations closed, 2026 delivery, two remote regional facilities, capacity up to 60, commissioning email.' },
      { kind: 'statement', label: 'Circuit Breaker media statement', url: 'https://statements.qld.gov.au/statements/103548', note: '18 Sep 2025 announcement, market engagement, non-government partners, north and south east locations.' },
      { kind: 'budget', label: 'Budget measure', url: 'https://budget.qld.gov.au/files/Budget-2025-26-BP4-Budget-Measures.pdf', note: 'Budget allocation for Circuit Breaker Sentencing.' },
      { kind: 'opendata', label: 'Budget measure open data', url: 'https://www.data.qld.gov.au/dataset/2025-26-state-budget-budget-paper-4-budget-measures', note: 'Machine-readable Budget Paper 4 source for the measure.' },
      { kind: 'statement', label: 'Budget media statement', url: 'https://statements.qld.gov.au/statements/102882', note: 'Named in the wider rehabilitation package.' },
      { kind: 'charter', label: 'Ministerial charter commitment', url: 'https://cabinet.qld.gov.au/ministers-portfolios/assets/charter-letter/laura-gerber.pdf', note: 'Premier letter says the minister must go to market for two secure, remote and effective centres.' },
      { kind: 'statement', label: 'Question on Notice 1145', url: 'https://documents.parliament.qld.gov.au/tableoffice/questionsanswers/2024/1145-2024.pdf', note: 'Asked about tender timing, cost, and probity; answer says tender process was set to occur as soon as possible.' },
      { kind: 'statement', label: 'Hansard, 18 Sep 2025', url: 'https://documents.parliament.qld.gov.au/events/han/2025/2025_09_18_WEEKLY.pdf', note: 'Ministerial statement to Parliament on market engagement and program model.' },
      { kind: 'report', label: 'QFCC Child Rights Report 2025', url: 'https://www.qfcc.qld.gov.au/sites/default/files/report-queensland-child-rights-report-2025.pdf', note: 'Independent concern about evaluation, implementation timelines, co-design, and equity analysis.' },
      { kind: 'report', label: 'QFCC performance report 2024-25', url: 'https://www.qfcc.qld.gov.au/sites/default/files/annual-report-on-the-performance-of-the-queensland-child-protection-system-2024-25.pdf', note: 'Independent reference to the three to six month alternative-to-detention model.' },
    ],
    matchingWorkflow: [
      'Treat the official program page as the current primary source and monitor it for post-ROI updates.',
      'Search QTenders, Queensland Contracts Directory, DYJVS disclosures, Hansard, QONs, and estimates for ROI, RFO, award, operator, and facility language.',
      'Keep the current live SQL row as budget visibility only: it proves a named DYJVS funding line, not provider delivery.',
      'When operators are named, resolve each to ABN, CivicGraph entity, ACNC/ASIC/ORIC record, funding history, board links, and public contact path.',
      'Build a court-pathway note from legislation, practice directions, Legal Aid/ATSILS advice, and published implementation guidance.',
    ],
    justiceHubOutreach: [
      'Ask DYJVS commissioning what can be made public about ROI, tender timing, operators, locations, evaluation, and reporting.',
      'Interview legal services and community advocates about whether courts can actually use the option and what safeguards are missing.',
      'Ask ACCOs, families, and place-based services what would make any residential alternative culturally safe, non-punitive, and genuinely diversionary.',
      'Collect stories about where children are currently remanded because community alternatives are unavailable, without exposing identities or court matters.',
    ],
    missingProof: ['operator names and ABNs', 'facility locations and community governance', 'procurement package, shortlist, or contract award', 'court eligibility and legal mechanism', 'service model and cultural authority', 'participant, completion, breach, reoffending, and detention-displacement data'],
    articleAngle: 'The promise is simple: a court-ordered path that keeps young people out of detention. The proof is whether the public can see who runs it, how courts use it, what safeguards exist, and whether it actually displaces detention.',
    centreOfExcellenceUse: 'Use this as the "how far we have to go" article hook: a Centre of Excellence should be able to connect announcements, court pathways, providers, lived experience, rights checks, and outcomes before the program is called a success.',
    publicBrief: {
      headline: 'The alternative-to-detention promise is clearer than the delivery trail.',
      intro: 'Circuit Breaker now has enough public detail to describe the model, but not enough to prove delivery. The current evidence says: $80m over four years, ROI closed, two remote regional facilities, up to 60 young people, 3 to 6 month court-sentenced rehabilitation, and delivery expected in 2026. The missing layer is who runs it, where, under what court power, with what safeguards, and with what outcomes.',
      readerNotes: [
        'Known: official program page, budget measure, charter letter, Question on Notice, Hansard, media statement, and a named DYJVS funding row exist.',
        'Not known yet: operators, ABNs, contracts, facility places, court eligibility, referral pathway, and performance measures.',
        'Accountability test: if this is genuinely an alternative to detention, the reporting must show detention displacement, completion, breaches, family/contact rights, cultural safety, and post-program outcomes.',
      ],
      usefulInformation: [
        'Public commissioning contact: YJCommissioning@youthjustice.qld.gov.au.',
        'Ask DYJVS for the public ROI/RFO trail, operator naming timeline, evaluation framework, and data that will be reported.',
        'Ask legal services how the sentencing order works in practice and whether children can refuse, appeal, breach, or be returned to detention.',
        'Ask community-controlled organisations what governance and cultural authority should look like before remote residential programs are treated as evidence-based.',
      ],
      civicLinks: [
        { kind: 'report', label: 'QLD youth justice ledger', href: '/reports/youth-justice/qld', note: 'State-level funding, outcomes, and program context.' },
        { kind: 'tracker', label: 'QLD announcement register', href: '/reports/youth-justice/qld/announcements', note: 'Compare Circuit Breaker with Staying on Track, Regional Reset, Kickstarter, and schools.' },
        { kind: 'admin', label: 'Provider matching trackers', href: '/reports/youth-justice/qld/trackers', note: 'Use this once operators or sites are named.' },
      ],
      adminActions: [
        'Create a Circuit Breaker watch query for QTenders, Queensland Contracts Directory, Hansard, QONs, estimates, and DYJVS page changes.',
        'Keep the current SQL match labelled as department budget visibility, not proof of provider delivery.',
        'Prepare a JusticeHub outreach list for DYJVS commissioning, Legal Aid Queensland, ATSILS, Youth Advocacy Centre, QFCC, and likely regional ACCOs.',
      ],
    },
  },
  {
    slug: 'youth-justice-schools',
    title: 'Youth Justice Schools',
    amountLabel: '$40m over 2 years',
    amountValue: 40_000_000,
    sourceLabel: '2025-26 Budget SDS',
    status: 'provider-sql',
    summary: 'Two schools for high-risk teens on youth justice orders in South East Queensland and North Queensland.',
    whyItMatters: 'Education is one of the clearest failure points before detention. These schools need to be connected to disengagement, exclusions, attendance, and justice contact data.',
    serviceAreas: ['alternative education', 'youth justice orders', 'crime prevention schools', 'school re-engagement', 'North Queensland', 'South East Queensland'],
    providerLeads: [
      {
        name: 'Ohana Education / Ohana for Youth',
        role: 'provider signal in the tracker and local contract mirror',
        source: 'Tracker evidence',
        status: 'tracker signal',
        entityStatus: 'linked',
        abn: '86633799124',
        gsId: 'AU-ABN-86633799124',
        knownFacts: ['QLD youth-justice snapshot links OHANA EDUCATION LTD to 1 General Goods and Services row worth about $1.7m', 'QLD lobbying register mirror contains Ohana for Youth'],
        askNext: ['Confirm whether Ohana Education Ltd is the contracting entity for Ohana for Youth', 'Confirm school site, cohort, enrolment, and transition model'],
        lockedInfo: ['student identities', 'school behaviour records', 'justice order details'],
        outreachAngle: 'Ask how the school model avoids becoming exclusion by another name and what success evidence can be shared.',
        contactEmail: 'executive@arcadia.qld.edu.au',
        contactPhone: '07 5655 1839',
        website: 'https://ohana.org.au',
      },
      {
        name: 'Men of Business',
        role: 'publicly discussed in crime-prevention-schools evidence chain',
        source: 'Tracker evidence',
        status: 'tracker signal',
        entityStatus: 'linked',
        abn: '41601774001',
        gsId: 'AU-ABN-41601774001',
        knownFacts: ['ABN Lookup resolves Men of Business Australia Limited to ABN 41 601 774 001', 'MOB Academy is operated by Men of Business Australia Ltd'],
        askNext: ['Confirm whether the role is provider, partner, school operator, or public reference point', 'Ask what can be shared about the crime-prevention-school model'],
        lockedInfo: ['student identities', 'unpublished operator agreements', 'school-level incident records'],
        outreachAngle: 'Resolve the entity first, then ask what the model is designed to do for young people pushed out of mainstream schooling.',
        contactEmail: 'enrolments@menofbusiness.com.au',
        contactPhone: '07 5613 2093',
        website: 'https://menofbusiness.com.au',
      },
    ],
    sourceLinks: [
      { kind: 'budget', label: 'Service Delivery Statement', url: 'https://budget.qld.gov.au/files/Budget-2025-26-SDS-Department-of-Youth-Justice-and-Victim-Support.pdf', note: 'SDS allocation for youth justice schools.' },
      { kind: 'statement', label: 'Budget media statement', url: 'https://statements.qld.gov.au/statements/102882', note: 'Named alongside Crime Prevention Schools.' },
      { kind: 'tracker', label: 'Tracker registry', url: '/reports/youth-justice/qld/trackers/crime-prevention-schools', note: 'Structured evidence chain with Hansard, QON, tender, and mirror traces.' },
      { kind: 'dossier', label: 'Crime Prevention Schools dossier', url: '/reports/youth-justice/qld/crime-prevention-schools', note: 'Specialist investigation page.' },
    ],
    matchingWorkflow: [
      'Join tracker evidence to provider rows and school site names.',
      'Resolve Ohana, Men of Business, and any site operators to entity records.',
      'Compare announced school model to actual tender, contract, and delivery geography.',
      'Cross-match with education disengagement, youth justice orders, and ALMA alternatives.',
    ],
    justiceHubOutreach: [
      'Ask young people, families, and educators what school exclusion looked like before justice contact.',
      'Ask providers how these schools differ from exclusion-by-another-name.',
      'Seek practice evidence on attendance, re-engagement, cultural safety, and transitions back to education.',
    ],
    missingProof: ['complete school operator list', 'confirmed sites', 'enrolment and attendance data', 'transition outcomes'],
    articleAngle: 'The question is whether new schools repair exclusion or institutionalise it under youth justice.',
    centreOfExcellenceUse: 'Use this as a CoE evidence case: youth justice reform has to join justice, education, family, and place data rather than track programs separately.',
  },
  {
    slug: 'kickstarter-early-intervention',
    title: 'Kickstarter early intervention',
    amountLabel: '$50m over 4 years',
    amountValue: 50_000_000,
    sourceLabel: '2025-26 Budget Paper 4',
    status: 'named-sql',
    summary: 'Research-backed early intervention models for at-risk young people, with 49 new programs described publicly by April 2026.',
    whyItMatters: 'Kickstarter is where the government is naming early intervention activity. It should become the first clean test of program evidence, provider geography, and story outcomes.',
    serviceAreas: ['early intervention', 'mentoring', 'vocational pathways', 'girls programs', 'place-based prevention', 'youth engagement'],
    providerLeads: [
      {
        name: 'Central Queensland Indigenous Development Limited',
        role: '$900k Kickstarter Grants row',
        source: 'Funding snapshot + ABN Lookup',
        status: 'sql signal',
        entityStatus: 'linked',
        abn: '60110812489',
        gsId: 'AU-ABN-60110812489',
        knownFacts: ['Named in the local QLD Kickstarter Grants snapshot', 'ABN Lookup resolves this to Central Queensland Indigenous Development Limited', 'CQID publishes youth services including Deadly Futures'],
        askNext: ['Confirm the Kickstarter program contact', 'Confirm Bundaberg, Rockhampton, and Woorabinda delivery model', 'Ask what evidence can be public'],
        outreachAngle: 'Contact as a resolved entity and ask what the $900k Kickstarter work is delivering and who can speak about it.',
        contactEmail: 'reception@cqid.com.au',
        contactPhone: '1800 000 307',
        website: 'https://cqid.com.au',
      },
      {
        name: 'Aspire Cairns Community Limited',
        role: '$300k Kickstarter Grants row',
        source: 'Funding snapshot',
        status: 'sql signal',
        entityStatus: 'linked',
        abn: '15651164082',
        gsId: 'AU-ABN-15651164082',
        knownFacts: ['Named in the local QLD Kickstarter Grants snapshot'],
        askNext: ['Confirm program contact', 'Ask what the Cairns delivery model is', 'Ask what evidence can be public'],
        outreachAngle: 'Contact as a known entity and ask for the right program lead for the Kickstarter activity.',
        contactEmail: 'julie.mcneil@aspireccl.com.au',
        contactPhone: '07 4053 5400',
        website: 'https://www.aspirecommunity.com.au',
      },
      {
        name: 'Bori Muy LTD',
        role: '$300k Kickstarter Grants row',
        source: 'Funding snapshot',
        status: 'sql signal',
        entityStatus: 'linked',
        abn: '43682387300',
        gsId: 'AU-ABN-43682387300',
        knownFacts: ['Named in the local QLD Kickstarter Grants snapshot'],
        askNext: ['Confirm program contact', 'Confirm service model and community authority'],
        outreachAngle: 'Contact as a known entity and ask what can be shared about the early intervention model.',
        contactEmail: 'admin@borimuy.com',
        website: 'https://www.borimuy.com.au',
      },
      {
        name: 'Indigenous Mana Academy / Indigenous Mana Limited',
        role: '$300k Kickstarter Grants row',
        source: 'Funding snapshot + ABN Lookup',
        status: 'sql signal',
        entityStatus: 'linked',
        abn: '82679578977',
        gsId: 'AU-ABN-82679578977',
        knownFacts: ['Named in the local QLD Kickstarter Grants snapshot', 'ABN Lookup resolves this to INDIGENOUS MANA LIMITED', 'Indigenous Mana publishes ABN and phone on its website'],
        askNext: ['Confirm the Indigenous Mana Academy program contact', 'Confirm Moreton Bay delivery place', 'Ask what evidence can be public'],
        outreachAngle: 'Contact as a resolved entity and ask who can speak about the funded Indigenous Mana Academy program.',
        contactPhone: '1800 YOUTHZ',
        website: 'https://indigenousmana.org.au',
      },
      {
        name: 'Jabalbina Yalanji Aboriginal Corporation',
        role: '$300k Kickstarter Grants row',
        source: 'Funding snapshot',
        status: 'sql signal',
        entityStatus: 'linked',
        abn: '79611886178',
        gsId: 'AU-ABN-79611886178',
        knownFacts: ['Named in the local QLD Kickstarter Grants snapshot'],
        askNext: ['Confirm Kickstarter program contact', 'Ask what should be public and what should remain community-held'],
        outreachAngle: 'Approach through consent-first practice and ask what Jabalbina wants documented.',
        contactEmail: 'reception@jabalbina.com.au',
        contactPhone: '07 4098 3552',
        website: 'https://www.jabalbina.com.au',
      },
      {
        name: 'Prosocial Skills Development',
        role: '$290k Kickstarter Grants row',
        source: 'Funding snapshot',
        status: 'sql signal',
        entityStatus: 'linked',
        abn: '26635173635',
        gsId: 'AU-ABN-26635173635',
        knownFacts: ['Named in the local QLD Kickstarter Grants snapshot'],
        askNext: ['Confirm program contact', 'Ask what intervention model is being delivered'],
        outreachAngle: 'Contact as a known entity and ask for a short description of the funded model and evidence.',
        contactEmail: 'prosocialskillsdevelopment@gmail.com',
      },
      {
        name: 'Thrive and Connect Pty Ltd',
        role: '$290k Kickstarter Grants row',
        source: 'Funding snapshot + ABN Lookup',
        status: 'sql signal',
        entityStatus: 'linked',
        abn: '69677779029',
        gsId: 'AU-ABN-69677779029',
        knownFacts: ['Named in the local QLD Kickstarter Grants snapshot', 'ABN Lookup resolves this to THRIVE & CONNECT PTY LTD', 'Thrive and Connect publishes info@thriveconnectaus.com'],
        askNext: ['Confirm the Thrive Guiding program contact', 'Confirm Cairns delivery model', 'Ask what evidence or story can be shared'],
        outreachAngle: 'Contact as a resolved entity and ask whether they can confirm the Kickstarter program lead.',
        contactEmail: 'info@thriveconnectaus.com',
        website: 'https://www.thriveconnectaus.com',
      },
      {
        name: 'Desert Pea Association Inc',
        role: '$285k Kickstarter Grants row',
        source: 'Funding snapshot',
        status: 'sql signal',
        entityStatus: 'linked',
        abn: '38854047029',
        gsId: 'AU-ABN-38854047029',
        knownFacts: ['Named in the local QLD Kickstarter Grants snapshot'],
        askNext: ['Confirm program contact', 'Ask what public evidence or story can be shared'],
        outreachAngle: 'Contact as a known entity and ask for consent-safe program evidence.',
        contactEmail: 'manager@desertpeamedia.com',
        website: 'https://www.desertpeamedia.com',
      },
      {
        name: 'Brodie Germaine Fitness Aboriginal Corporation',
        role: '$280k Kickstarter Grants row',
        source: 'Funding snapshot + ABN Lookup',
        status: 'sql signal',
        entityStatus: 'linked',
        abn: '94770726134',
        gsId: 'AU-ABN-94770726134',
        knownFacts: ['Named in the local QLD Kickstarter Grants snapshot', 'ABN Lookup resolves this to Brodie Germaine Fitness Aboriginal Corporation'],
        askNext: ['Confirm program contact', 'Ask what the youth engagement model is'],
        outreachAngle: 'Contact as a known entity and ask how the program supports young people before justice contact escalates.',
        contactEmail: 'brodiegermainefitness@gmail.com',
        contactPhone: '0411 388 526',
        website: 'https://www.brodiegermainefitness.com',
      },
      {
        name: 'Silver Lining Foundation Australia Ltd',
        role: '$275k Kickstarter Grants row',
        source: 'Funding snapshot + ABN Lookup',
        status: 'sql signal',
        entityStatus: 'linked',
        abn: '92625056108',
        gsId: 'AU-ABN-92625056108',
        knownFacts: ['Named in the local QLD Kickstarter Grants snapshot', 'ABN Lookup resolves this to SILVER LINING FOUNDATION AUSTRALIA LTD', 'ABN Lookup lists Silver Lining School business names under this entity'],
        askNext: ['Confirm the Out of Hours Support program contact', 'Confirm Townsville delivery place', 'Ask what should be public and what should remain consent-held'],
        outreachAngle: 'Contact as a resolved entity and ask for the correct program contact for the Out of Hours Support program.',
        contactEmail: 'info@silverlining.org.au',
        contactPhone: '1300 OURMOB',
        website: 'https://silverlining.org.au',
      },
      {
        name: 'NQ Ummah Care Ltd',
        role: '$146k Kickstarter Grants row',
        source: 'Funding snapshot + ABN Lookup',
        status: 'sql signal',
        entityStatus: 'linked',
        abn: '95636275075',
        gsId: 'AU-ABN-95636275075',
        knownFacts: ['Named in the local QLD Kickstarter Grants snapshot', 'ABN Lookup resolves this to NQ UMMAH CARE LTD', 'NQ Ummah Care publishes admin@nquc.org on its website'],
        askNext: ['Confirm the Pathways to Engagement program contact', 'Confirm Townsville delivery community', 'Ask what evidence or story can be shared'],
        outreachAngle: 'Contact as a resolved entity and ask what the Pathways to Engagement program is doing and who can speak about it.',
        contactEmail: 'admin@nquc.org',
        website: 'https://www.nquc.org',
      },
      {
        name: 'Lookout 07',
        role: '$131k Kickstarter Grants row',
        source: 'Funding snapshot',
        status: 'sql signal',
        entityStatus: 'linked',
        abn: '87666455661',
        gsId: 'AU-ABN-87666455661',
        knownFacts: ['Named in the local QLD Kickstarter Grants snapshot'],
        askNext: ['Confirm program contact', 'Ask what model and outcomes can be shared'],
        outreachAngle: 'Contact as a known entity and ask for the right person to explain the funded work.',
        contactEmail: 'mark@lookout07.org.au',
        contactPhone: '0431 016 488',
        website: 'https://lookout07.org.au',
      },
    ],
    sourceLinks: [
      { kind: 'budget', label: 'Budget measure', url: 'https://budget.qld.gov.au/files/Budget-2025-26-BP4-Budget-Measures.pdf', note: 'Budget allocation for Kickstarter.' },
      { kind: 'statement', label: 'Official Kickstarter program page', url: 'https://www.youthjustice.qld.gov.au/partnerships/kickstarter-grants', note: 'Queensland Government page listing funded Kickstarter programs, locations, and project descriptions.' },
      { kind: 'statement', label: 'Round one providers', url: 'https://statements.qld.gov.au/statements/103461', note: 'Round one public provider context.' },
      { kind: 'statement', label: 'Cairns example', url: 'https://statements.qld.gov.au/statements/104349', note: 'Cairns program example.' },
      { kind: 'statement', label: 'Townsville example', url: 'https://statements.qld.gov.au/statements/104341', note: 'Townsville program example.' },
      { kind: 'statement', label: 'Wide Bay update', url: 'https://statements.qld.gov.au/statements/104827', note: 'Public statement says 49 new Kickstarter programs by 29 April 2026.' },
    ],
    matchingWorkflow: [
      'Extract every named Kickstarter provider from statements and funding rows.',
      'Match provider names to QLD youth justice funding, ACNC, ABN, GHL contacts, and local entity records.',
      'Tag each provider by model type: mentoring, sport, culture, education, family, vocational, or specialist support.',
      'Prioritise outreach where program has public delivery claims but no outcomes evidence.',
    ],
    justiceHubOutreach: [
      'Ask providers what evidence makes their intervention research-backed.',
      'Ask what young people would say changed because of the program.',
      'Invite providers to contribute a JusticeHub story, method note, or practice evidence entry.',
    ],
    missingProof: ['complete provider list for all 49 programs', 'amount per provider', 'model and evidence basis', 'participant and outcome reporting'],
    articleAngle: 'Kickstarter lets the article move from outrage to testable prevention: what did Queensland actually fund before a young person reached detention?',
    centreOfExcellenceUse: 'Use Kickstarter as the first candidate pipeline for a JusticeHub Centre of Excellence evidence library.',
    publicBrief: {
      headline: 'Queensland says it is funding early intervention. We are checking what that means in real places.',
      intro:
        'Kickstarter is a named Queensland youth justice program for early intervention. The public record says new programs are being rolled out, but it still needs to show who is funded, where they work, what model they use, what evidence sits behind the claim, and what young people, families, and communities say is changing.',
      readerNotes: [
        'This matters because early intervention is where the system should act before police, court, remand, or detention become the main response.',
        'The first question is not whether money was announced. It is whether local services, funding, evidence, and outcomes can be seen and checked.',
        'JusticeHub can use this page to invite providers and communities into a clearer public record, without asking for private case files.',
      ],
      usefulInformation: [
        'program name, location, and delivery organisation',
        'ABN or legal entity for the funded provider',
        'who can be referred and how referral happens',
        'the service model: mentoring, culture, sport, education, family support, vocational pathway, or specialist support',
        'what evidence or community feedback shows the program is helping',
        'what information must stay private, consent-held, or community-held',
      ],
      civicLinks: [
        { kind: 'report', label: 'QLD youth justice ledger', href: '/reports/youth-justice/qld', note: 'Spending, outcomes, ALMA coverage, and announcement-vs-delivery context.' },
        { kind: 'tracker', label: 'Announcement register', href: '/reports/youth-justice/qld/announcements', note: 'All named 2025-26 youth justice commitments in one working register.' },
        { kind: 'entity', label: 'Entity search', href: '/entity', note: 'Resolve providers to ABNs, GS IDs, charity records, contracts, grants, and relationships.' },
        { kind: 'tracker', label: 'Tracker registry', href: '/reports/youth-justice/qld/trackers', note: 'Structured evidence trails for source material, tenders, statements, and gaps.' },
        { kind: 'report', label: 'National youth justice map', href: '/reports/youth-justice', note: 'Place Kickstarter inside the wider national youth justice evidence picture.' },
        { kind: 'funding', label: 'Funding search', href: '/grants?type=open_opportunity&search=youth%20justice', note: 'Use live funding search to find related youth justice and prevention opportunities.' },
      ],
      adminActions: [
        'extract every named Kickstarter provider from statements and funding rows',
        'resolve each provider to ABN, GS ID, ACNC/ASIC/ORIC record, and GHL contact',
        'tag the model type and delivery place for each provider',
        'mark what is public, what is sensitive, and what still needs asking',
        'record response status after outreach: open to talk, referred, follow-up, no response, or declined',
      ],
    },
  },
  {
    slug: 'gold-standard-proven-initiatives',
    title: 'Gold Standard proven initiatives',
    amountLabel: '$65m over 5 years',
    amountValue: 65_000_000,
    sourceLabel: '2025-26 Budget Paper 4',
    status: 'official-only',
    summary: 'Community-led and outcomes-focused programs that reduce youth offending.',
    whyItMatters: 'The phrase "proven initiatives" should not stay rhetorical. It needs a public evidence standard and a visible provider list.',
    serviceAreas: ['proven initiatives', 'community-led programs', 'youth offending reduction', 'outcomes funding', 'evidence standards'],
    providerLeads: [
      {
        name: 'Expression-of-interest applicants',
        role: 'first $5m EOI opened publicly',
        source: 'Ministerial statement',
        status: 'needs confirmation',
        entityStatus: 'system-actor',
      },
    ],
    sourceLinks: [
      { kind: 'budget', label: 'Budget measure', url: 'https://budget.qld.gov.au/files/Budget-2025-26-BP4-Budget-Measures.pdf', note: 'Budget allocation for Gold Standard proven initiatives.' },
      { kind: 'statement', label: 'Budget media statement', url: 'https://statements.qld.gov.au/statements/102882', note: 'Named in early intervention and rehabilitation package.' },
      { kind: 'statement', label: 'Proven Initiatives EOI', url: 'https://statements.qld.gov.au/statements/103460', note: 'First expression-of-interest round opened.' },
    ],
    matchingWorkflow: [
      'Track EOI announcements and award notices.',
      'Extract funded model, provider, location, cohort, and evidence claims.',
      'Compare claims to ALMA evidence and JusticeHub method notes.',
      'Build a public evidence-grade field for each funded initiative.',
    ],
    justiceHubOutreach: [
      'Ask providers what proof they use and who validates it.',
      'Ask communities what outcomes matter beyond reoffending.',
      'Ask whether evidence is owned by community, government, university, or provider.',
    ],
    missingProof: ['EOI winners', 'definition of proven', 'provider list', 'outcomes framework'],
    articleAngle: 'If the state says it will fund what works, the public should see the standard for what counts as working.',
    centreOfExcellenceUse: 'This is the natural bridge into the Centre of Excellence piece: Queensland needs shared evidence infrastructure, not one-off proof claims.',
  },
  {
    slug: 'regional-reset',
    title: 'Regional Reset',
    amountLabel: '$50m over 4 years',
    amountValue: 50_000_000,
    sourceLabel: 'Ministerial statement, 23 Oct 2025',
    status: 'provider-sql',
    summary: 'Nine-location intensive early intervention program, with Youth Insearch publicly named for Central Queensland and Moreton Bay.',
    whyItMatters: 'Regional Reset is a place-based promise. It should be testable against regional detention, remand, police contact, school disengagement, and service deserts.',
    serviceAreas: ['regional intervention', 'place-based prevention', 'youth engagement', 'peer support', 'family support', 'regional service deserts'],
    providerLeads: [
      {
        name: 'Youth Insearch',
        role: 'publicly named for Central Queensland and Moreton Bay',
        source: 'Ministerial statements',
        status: 'named publicly',
        entityStatus: 'linked',
        abn: '31886363881',
        gsId: 'AU-ABN-31886363881',
        knownFacts: ['QLD youth-justice snapshot links 1 Social Services row worth about $5.5m', 'QLD lobbying register mirror contains Youth Insearch'],
        askNext: ['Confirm whether the Social Services row maps to Regional Reset', 'Ask which of the nine locations are active and what referral pathway exists'],
        lockedInfo: ['young person identities', 'regional caseloads not cleared for publication', 'family histories'],
        outreachAngle: 'Ask what regional support looks like before police or court contact and what evidence can be shared safely.',
        contactEmail: 'donna.ryan@youthinsearch.org.au',
        contactPhone: '1800 805 635',
        website: 'https://www.youthinsearch.org.au',
      },
      {
        name: 'Nine target locations',
        role: 'location set named at program level',
        source: 'Ministerial statement',
        status: 'needs confirmation',
        entityStatus: 'system-actor',
        knownFacts: ['The program is place-based, but not every provider/location pair is currently visible in the snapshot'],
        askNext: ['List each target location', 'Resolve provider and local partner for each location', 'Match against LGA burden and service desert data'],
        lockedInfo: ['site-level risk details', 'individual young person details', 'unpublished police or court data'],
        outreachAngle: 'Use the places as the interview map: every location should have a service trail and a community account of what changed.',
      },
    ],
    sourceLinks: [
      { kind: 'statement', label: 'Stakeholder sessions', url: 'https://statements.qld.gov.au/statements/101911', note: 'Early process for Regional Reset and Staying on Track.' },
      { kind: 'statement', label: 'Tenders opened', url: 'https://statements.qld.gov.au/statements/102167', note: 'Tender process announced.' },
      { kind: 'statement', label: 'Regional Reset launch', url: 'https://statements.qld.gov.au/statements/103764', note: 'Nine-location model and Youth Insearch named.' },
      { kind: 'statement', label: 'Moreton Bay rollout', url: 'https://statements.qld.gov.au/statements/103857', note: 'Youth Insearch named for Moreton Bay delivery.' },
      { kind: 'budget', label: 'Budget measure', url: 'https://budget.qld.gov.au/files/Budget-2025-26-BP4-Budget-Measures.pdf', note: 'Budget allocation for Regional Reset.' },
    ],
    matchingWorkflow: [
      'Resolve each target location and provider to place/entity records.',
      'Search Youth Insearch in SQL, grants, GHL, ACNC, and public statements.',
      'Join to LGA burden scores, ALMA interventions, and youth justice outcomes by region.',
      'Create one story lead per target location where the service trail is visible.',
    ],
    justiceHubOutreach: [
      'Ask Youth Insearch what regional service gaps they are seeing.',
      'Ask regional providers what changed after program launch.',
      'Invite young people and workers to describe what support exists before police or court contact.',
    ],
    missingProof: ['contracts for nine locations', 'all providers', 'participant counts', 'region-by-region outcomes'],
    articleAngle: 'Regional Reset should show whether Queensland is funding help where children live, or just naming regions after harm has concentrated there.',
    centreOfExcellenceUse: 'Use the regional spread to show why a Centre of Excellence needs place intelligence, not only program descriptions.',
  },
  {
    slug: 'crime-prevention-schools',
    title: 'Crime Prevention Schools',
    amountLabel: '$50m over 5 years',
    amountValue: 50_000_000,
    sourceLabel: '2025-26 Budget SDS',
    status: 'provider-sql',
    summary: 'Schools intended to re-engage young people who have disengaged from mainstream education and are at risk of crime.',
    whyItMatters: 'This is the direct link between education exclusion and youth justice. The program needs a transparent school, provider, tender, and outcome chain.',
    serviceAreas: ['school re-engagement', 'alternative education', 'crime prevention', 'school exclusion', 'tendered school models'],
    providerLeads: [
      {
        name: 'Ohana Education / Ohana for Youth',
        role: 'appears in contract and tracker evidence',
        source: 'Tracker evidence',
        status: 'tracker signal',
        entityStatus: 'linked',
        abn: '86633799124',
        gsId: 'AU-ABN-86633799124',
        knownFacts: ['QLD youth-justice snapshot links OHANA EDUCATION LTD to 1 General Goods and Services row worth about $1.7m', 'Tracker evidence links Ohana to the crime prevention school trail'],
        askNext: ['Confirm contract and site', 'Ask for evidence of attendance, transition, consent, and student support model'],
        lockedInfo: ['student identities', 'school records', 'unpublished referral data'],
        outreachAngle: 'Ask whether the model repairs school exclusion or simply moves young people into another justice-labelled institution.',
        contactEmail: 'executive@arcadia.qld.edu.au',
        contactPhone: '07 5655 1839',
        website: 'https://ohana.org.au',
      },
      {
        name: 'Men of Business',
        role: 'publicly named in source trail',
        source: 'Tracker evidence',
        status: 'tracker signal',
        entityStatus: 'linked',
        abn: '41601774001',
        gsId: 'AU-ABN-41601774001',
        knownFacts: ['ABN Lookup resolves Men of Business Australia Limited to ABN 41 601 774 001', 'MOB Academy is operated by Men of Business Australia Ltd'],
        askNext: ['Confirm role in the school model and any delivery geography', 'Ask what practice evidence would show whether the school model is working'],
        lockedInfo: ['student identities', 'internal school records', 'private delivery agreements'],
        outreachAngle: 'Resolve the entity, then ask what practice evidence would show whether the school model is working.',
        contactEmail: 'enrolments@menofbusiness.com.au',
        contactPhone: '07 5613 2093',
        website: 'https://menofbusiness.com.au',
      },
    ],
    sourceLinks: [
      { kind: 'budget', label: 'Service Delivery Statement', url: 'https://budget.qld.gov.au/files/Budget-2025-26-SDS-Department-of-Youth-Justice-and-Victim-Support.pdf', note: 'SDS allocation for Crime Prevention Schools.' },
      { kind: 'statement', label: 'Budget media statement', url: 'https://statements.qld.gov.au/statements/102882', note: 'Named as education-linked youth justice initiative.' },
      { kind: 'tracker', label: 'Tracker evidence chain', url: '/reports/youth-justice/qld/trackers/crime-prevention-schools', note: 'Hansard, QON, tender, award, and rollout traces.' },
      { kind: 'dossier', label: 'Investigation dossier', url: '/reports/youth-justice/qld/crime-prevention-schools', note: 'Specialist story surface.' },
    ],
    matchingWorkflow: [
      'Use the tracker as the source-of-truth timeline.',
      'Extract all provider and site names from Hansard, QON, tender, award, and rollout records.',
      'Match providers to education and youth justice signals.',
      'Turn unresolved providers into outreach tasks for JusticeHub story gathering.',
    ],
    justiceHubOutreach: [
      'Ask young people what mainstream school disengagement felt like before justice contact.',
      'Ask providers what success looks like beyond attendance.',
      'Ask educators and families what accountability should exist for alternative school models.',
    ],
    missingProof: ['complete award list', 'site-level enrolments', 'attendance and transition outcomes', 'link to justice contact reduction'],
    articleAngle: 'This is the concrete Brennan-counterpart evidence: how far we have to go is visible when school failure becomes youth justice infrastructure.',
    centreOfExcellenceUse: 'Use this as the first named case study in the JusticeHub Centre of Excellence roadmap.',
  },
  {
    slug: 'youth-co-response-models',
    title: 'Youth Co-response Models',
    amountLabel: '$75m over 4 years',
    amountValue: 75_000_000,
    sourceLabel: '2025-26 Budget Paper 4',
    status: 'not-visible',
    summary: 'Models intended to target crime hotspots and enhance community safety.',
    whyItMatters: 'Co-response can mean diversion, outreach, policing, health, or surveillance. It must be separated into who attends, what happens, and whether children are helped away from detention.',
    serviceAreas: ['co-response', 'hotspot response', 'police partnership', 'after-hours outreach', 'diversion', 'community safety'],
    providerLeads: [
      {
        name: 'Police, department, and community providers',
        role: 'delivery roles implied but not yet separated',
        source: 'Budget material',
        status: 'needs confirmation',
        entityStatus: 'system-actor',
      },
    ],
    sourceLinks: [
      { kind: 'budget', label: 'Budget measure', url: 'https://budget.qld.gov.au/files/Budget-2025-26-BP4-Budget-Measures.pdf', note: 'Budget allocation for co-response models.' },
      { kind: 'statement', label: 'Budget media statement', url: 'https://statements.qld.gov.au/statements/102882', note: 'Named in youth justice package.' },
    ],
    matchingWorkflow: [
      'Search program rows for co-response, hotspot, outreach, police, and diversion terms.',
      'Separate government-operated activity from contracted provider work.',
      'Map hotspots to LGAs and youth justice outcome burden.',
      'Look for provider media releases and local council mentions.',
    ],
    justiceHubOutreach: [
      'Ask community services whether co-response brings support or policing into families lives.',
      'Ask young people what happens during a co-response contact.',
      'Ask providers what data is recorded and who owns it.',
    ],
    missingProof: ['delivery split between police/department/providers', 'hotspot locations', 'provider list', 'contact and diversion outcomes'],
    articleAngle: 'The same phrase can hide two futures: care arriving earlier, or enforcement arriving faster.',
    centreOfExcellenceUse: 'Use co-response as a governance warning for the Centre of Excellence: evidence must distinguish support from surveillance.',
  },
  {
    slug: 'intensive-case-management',
    title: 'Intensive Case Management',
    amountLabel: '$38.8m over 4 years',
    amountValue: 38_800_000,
    sourceLabel: '2025-26 Budget Paper 4',
    status: 'official-only',
    summary: 'Tailored evidence-based support for high-risk youth, including serious repeat offenders.',
    whyItMatters: 'ICM is often where the highest-risk cohort is named, but the public cannot assess whether support is early, intensive, culturally safe, or simply compliance management.',
    serviceAreas: ['intensive case management', 'serious repeat offenders', 'high-risk youth', 'family support', 'case coordination'],
    providerLeads: [
      {
        name: 'Existing and expanded ICM delivery sites',
        role: 'program exists in public language but needs refreshed 2025-26 provider mapping',
        source: 'Ministerial and budget material',
        status: 'needs confirmation',
        entityStatus: 'system-actor',
      },
    ],
    sourceLinks: [
      { kind: 'budget', label: 'Budget measure', url: 'https://budget.qld.gov.au/files/Budget-2025-26-BP4-Budget-Measures.pdf', note: 'Budget allocation for ICM.' },
      { kind: 'statement', label: 'Budget media statement', url: 'https://statements.qld.gov.au/statements/102882', note: 'Named in youth justice package.' },
      { kind: 'statement', label: 'Earlier ICM expansion', url: 'https://statements.qld.gov.au/statements/101546', note: 'Existing program context before the 2025-26 package.' },
    ],
    matchingWorkflow: [
      'Search for intensive case management in old and current funding rows.',
      'Separate legacy ICM rows from new 2025-26 expansion funding.',
      'Resolve sites, providers, and government delivery units.',
      'Cross-match ICM locations against repeat contact and remand burden.',
    ],
    justiceHubOutreach: [
      'Ask workers what high-risk support requires in practice.',
      'Ask families whether case management felt supportive, punitive, or both.',
      'Ask whether ICM can produce anonymised practice lessons for JusticeHub.',
    ],
    missingProof: ['new 2025-26 provider rows', 'sites and cohorts', 'caseload numbers', 'outcomes for repeat contact'],
    articleAngle: 'Intensive support only matters if it arrives before detention becomes the default case plan.',
    centreOfExcellenceUse: 'Use ICM to show why the CoE needs practice learning, not just program counts.',
  },
  {
    slug: 'bail-programs',
    title: 'Bail Programs',
    amountLabel: '$44.3m over 4 years',
    amountValue: 44_300_000,
    sourceLabel: '2025-26 Budget Paper 4',
    status: 'named-sql',
    summary: 'Programs intended to support bail compliance by young people, including additional and internal departmental funding.',
    whyItMatters: 'Bail is where remand pressure becomes visible. Queensland has extremely high unsentenced detention; bail support should be assessed against remand, not only grant activity.',
    serviceAreas: ['bail support', 'remand reduction', 'court support', 'family support', 'compliance support', 'regional bail services'],
    providerLeads: [
      {
        name: 'South West Bail Support Service',
        role: 'named SQL delivery row visible',
        source: 'Funding snapshot',
        status: 'sql signal',
        entityStatus: 'linked',
        abn: '78793694389',
        gsId: 'AU-ABN-78793694389',
        knownFacts: ['Funding snapshot includes Toowoomba and Remote South West Bail Support rows worth about $966k across Bail Support Program and Service'],
        askNext: ['Confirm provider legal name behind the service label', 'Ask what blocks bail compliance in the region'],
        lockedInfo: ['court details', 'youth identities', 'case plan records'],
        outreachAngle: 'Use this as a remand-pressure interview: what support would have kept children out of custody?',
        contactEmail: 'hello@catholiccare.services',
        contactPhone: '1300 477 433',
        website: 'https://www.catholiccare.services',
      },
      {
        name: 'Cairns and Yarrabah Youth Bail Support Service',
        role: 'named SQL delivery row visible',
        source: 'Funding snapshot',
        status: 'sql signal',
        entityStatus: 'linked',
        abn: '34797758772',
        gsId: 'AU-ABN-34797758772',
        knownFacts: ['Funding snapshot includes Bail Support Program and Service rows worth about $3.7m'],
        askNext: ['Confirm delivery organisation and local partners', 'Ask how Yarrabah-specific cultural authority and family support are handled'],
        lockedInfo: ['young person identities', 'court outcomes not cleared for release', 'family contact details'],
        outreachAngle: 'Ask what makes bail support work in Cairns and Yarrabah and what evidence should be public.',
        contactEmail: 'referrals@yeti.net.au',
        contactPhone: '07 4051 4927',
        website: 'https://yeti.net.au/programs/cairns-and-yarrabah-youth-bail-support-service/',
      },
      {
        name: 'MY JUST Bail Support Service',
        role: 'Mt Isa and Mackay rows visible',
        source: 'Funding snapshot',
        status: 'sql signal',
        entityStatus: 'linked',
        abn: '99008610035',
        gsId: 'AU-ABN-99008610035',
        knownFacts: ['Funding snapshot includes Mt Isa and Mackay rows worth about $2.8m across Bail Support Program and Service'],
        askNext: ['Confirm provider owner and regional delivery model', 'Ask what happens between court, family, and community services after bail'],
        lockedInfo: ['court and compliance details', 'youth/family identities', 'private service notes'],
        outreachAngle: 'Use Mt Isa and Mackay as place-specific bail support stories tied to remand reduction.',
        contactEmail: 'qld@54reasons.org.au',
        contactPhone: '07 3199 0500',
        website: 'https://www.savethechildren.org.au/contact-us',
      },
      {
        name: 'Mercy Community Services',
        role: 'Cherbourg and South Burnett bail support row visible',
        source: 'Funding snapshot',
        status: 'sql signal',
        entityStatus: 'linked',
        abn: '51166477318',
        gsId: 'AU-ABN-51166477318',
        knownFacts: ['Funding snapshot links Mercy Community Services to Cherbourg/South Burnett bail rows worth about $2.0m including a named YJ_CON row'],
        askNext: ['Confirm current 2025-26 delivery status', 'Ask what bail support outcomes are tracked and what can be shared'],
        lockedInfo: ['client identities', 'court conditions', 'unpublished provider performance data'],
        outreachAngle: 'Ask what the public should understand about keeping young people safely in community while bail is active.',
        contactPhone: '07 4168 2921',
        website: 'https://mercycommunity.org.au',
      },
    ],
    sourceLinks: [
      { kind: 'budget', label: 'Budget measure', url: 'https://budget.qld.gov.au/files/Budget-2025-26-BP4-Budget-Measures.pdf', note: 'Budget allocation for bail programs.' },
      { kind: 'statement', label: 'Budget media statement', url: 'https://statements.qld.gov.au/statements/102882', note: 'Named in the youth justice package.' },
      { kind: 'dossier', label: 'QLD state report ledger', url: '/reports/youth-justice/qld', note: 'SQL signal and matched rows visible in the delivery ledger.' },
    ],
    matchingWorkflow: [
      'Treat bail as the benchmark because it already has visible named SQL rows.',
      'Resolve every named bail service to provider entity, ABN, place, and current status.',
      'Compare service geography to remand burden and detention rates.',
      'Use the pattern to improve missing-match logic for other announcements.',
    ],
    justiceHubOutreach: [
      'Ask bail providers what stops children from getting or keeping bail.',
      'Ask families what support would have prevented remand.',
      'Ask providers whether they can share anonymised practice stories about successful bail support.',
    ],
    missingProof: ['clean 2025-26 acquittal split', 'provider-level remand outcomes', 'court/referral pathway', 'community-controlled share'],
    articleAngle: 'Bail support is where the remand crisis becomes measurable: if funded support is visible, remand should be the outcome test.',
    centreOfExcellenceUse: 'Use bail as the proof-of-method for the CoE: link spending, provider, place, and outcome rather than treating them as separate reports.',
  },
];

export function qldAnnouncementSlugForProgram(program: string) {
  return program
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

export function qldAnnouncementHrefForProgram(program: string) {
  return `/reports/youth-justice/qld/announcements/${qldAnnouncementSlugForProgram(program)}`;
}

export function getQldAnnouncement(slug: string) {
  return qldYouthJusticeAnnouncements.find((item) => item.slug === slug);
}

export function qldAnnouncementStatusLabel(status: QldAnnouncement['status']) {
  const labels: Record<QldAnnouncement['status'], string> = {
    'named-sql': 'Named SQL visible',
    'provider-sql': 'Provider SQL signal',
    'official-only': 'Official evidence only',
    'not-visible': 'Not visible in SQL',
  };
  return labels[status];
}

export function qldAnnouncementStatusClass(status: QldAnnouncement['status']) {
  const styles: Record<QldAnnouncement['status'], string> = {
    'named-sql': 'border-emerald-300 bg-emerald-50 text-emerald-800',
    'provider-sql': 'border-blue-300 bg-blue-50 text-blue-800',
    'official-only': 'border-amber-300 bg-amber-50 text-amber-800',
    'not-visible': 'border-red-300 bg-red-50 text-red-800',
  };
  return styles[status];
}
